In [2]:
import pandas as pd

In [24]:
df = pd.read_excel('file1/scores1.xlsx', index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [26]:
# df.reset_index(drop=True, inplace=True)
# df

In [27]:
# df.describe()
# df.info()

In [28]:
# df['국어'].max()
# df['국어'].min()
# df['국어'].mean()
# df['국어'].std()

In [29]:
df.set_index('이름', inplace=True)
df.sort_index(ascending=False)

       학교    키   국어   영어   수학  과학  사회        SW특기
이름
승근열  디지털고  190  100   85   90  95  95          C#
박혜정  디지털고  188   55   65   45  40  35      PYTHON
박동현  디지털고  202   80  100   95  85  80           C
김재욱   구로고  188   15   20   10  35  10         NaN
김수찬   구로고  187   40   60   70  75  80         NaN
강호림   구로고  168   80   75   70  80  75  Javascript
강태원   구로고  184   40   35   50  55  25        Java
강나래   구로고  197   90   85  100  95  85      Python