In [2]:
import pandas as pd

In [4]:
df = pd.read_excel('file1/scores1.xlsx', index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
df.columns
# df.columns[0]
# df.columns[[0, 2]]

Index(['이름', '키'], dtype='str')

In [23]:
# df['이름']
# df[['이름', '학교']]
# df[df.columns[0:4]]
df.loc[:, '이름':'수학']
df[df.columns[-1]]
df[df.columns[[0,3,5]]]
df.iloc[3]

이름      김수찬
학교      구로고
키       187
국어       40
영어       60
수학       70
과학       75
사회       80
SW특기    NaN
Name: 4번, dtype: object

In [41]:
# df.loc[['1번', '5번']]
# df.loc['1번':'5번']
# df.loc['1번':'2번' , '이름':'수학']
# df.iloc[0]
# df.iloc[0:4]
# df.iloc[[0,1,4]]
df.iloc[0:4, 1:5]

       학교    키  국어  영어
지원번호
1번    구로고  197  90  85
2번    구로고  184  40  35
3번    구로고  168  80  75
4번    구로고  187  40  60

In [50]:
# df[df['국어']>=80]
# df.loc[df['키']>190, '학교':'수학']
df[(df['키']>=190) & (df['국어']>=90)]
df[(df['키']>=190) | (df['국어']>=90)]

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85  Python
6번    박동현  디지털고  202   80  100   95  85  80       C
8번    승근열  디지털고  190  100   85   90  95  95      C#