In [51]:
import pandas as pd
df = pd.read_excel('file1/scores1.xlsx', index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [13]:
# df['학교'] = df['학교']+'등학교'
# df['학교'] = df['학교'].str.replace('고교', '고')

In [20]:
# df['키'] = df['키'].astype(str)
# df['키'] = df['키']+'cm'
# df['키'] = df['키'].str.replace('cm', '')
# df['키'] = df['키'].astype(float)

### 함수 적용

In [22]:
# def add_cm(h):
#     return str(h)+'cm'

# df['키'] = df['키'].apply(add_cm)
# df

In [50]:
# def lowChange(s):
#     if pd.notnull(s):
#         return str(s).lower()
#     return '없음'

# df['SW특기'] = df['SW특기'].apply(lowChange)
# df

In [53]:
df['합계'] = df['국어'] + df['영어'] + df['수학'] + df['과학'] + df['사회']
df['평균'] = df['합계'] / 5
df['등급'] = 0
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계    평균  등급
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455  91.0   0
2번    강태원   구로고  184   40   35   50  55  25        Java  205  41.0   0
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380  76.0   0
4번    김수찬   구로고  187   40   60   70  75  80         NaN  325  65.0   0
5번    김재욱   구로고  188   15   20   10  35  10         NaN   90  18.0   0
6번    박동현  디지털고  202   80  100   95  85  80           C  440  88.0   0
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240  48.0   0
8번    승근열  디지털고  190  100   85   90  95  95          C#  465  93.0   0

In [40]:
# def Grade(x):
#     if x >= 90:
#         return 'A'
#     elif x >= 80:
#         return 'B'
#     elif x >= 70:
#         return 'C'
#     elif x >= 60:
#         return 'D'
#     else:
#         return 'F'

# df['등급'] = df['평균'].apply(Grade)
# df

In [54]:
df['등수'] = df['합계'].rank(ascending=False, method='min').astype(int)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계    평균  등급  등수
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455  91.0   0   2
2번    강태원   구로고  184   40   35   50  55  25        Java  205  41.0   0   7
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380  76.0   0   4
4번    김수찬   구로고  187   40   60   70  75  80         NaN  325  65.0   0   5
5번    김재욱   구로고  188   15   20   10  35  10         NaN   90  18.0   0   8
6번    박동현  디지털고  202   80  100   95  85  80           C  440  88.0   0   3
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240  48.0   0   6
8번    승근열  디지털고  190  100   85   90  95  95          C#  465  93.0   0   1