In [30]:
import pandas as pd
df = pd.read_excel('file1/students.xlsx', index_col='번호')
df['합계'] = df['국어'] + df['영어'] + df['수학']
df['평균'] = df['합계'] / 3
df['결과'] = '불합격'
df.loc[df['평균'] >= 70, '결과'] = '합격'
df.value_counts('결과')
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계         평균   결과
번호
1      Eadmund   신림고   2  171  56  92  60       c  208  69.333333  불합격
2       Kirbee   구로고   1  199  53  10  45       C  108  36.000000  불합격
3    Appolonia   구로고   3  193  77  52  81       C  210  70.000000   합격
4        Avery   구로고   2  187  59  35  43       C  137  45.666667  불합격
5       Dallis  디지털고   1  209  97  57  76       C  230  76.666667   합격
..         ...   ...  ..  ...  ..  ..  ..     ...  ...        ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213  71.000000   합격
97        Nada   구로고   3  170  60  89  55  PYTHON  204  68.000000  불합격
98       Fiona   신림고   1  200  97  95  84       C  276  92.000000   합격
99        Leif   구로고   2  192  96  84  34  PYTHON  214  71.333333   합격
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227  75.666667   합격

[100 rows x 11 columns]

In [33]:
filt1 = df['수학'] < 80
# df.drop(df[filt1].index)
# df[filt1].count()
# df2 = df[filt1]
# df2 = df[~filt1]
# df2

In [35]:
# df.drop(index=df[df['수학'] < 80].index)
# df.drop(index=df[df['수학'] < 80].index, inplace=True)
# df

In [45]:
df.columns
df2 = df[['이름', '국어', '영어', '수학', '합계']]
filt2 = df2['합계'] >= 200
df2[filt2].count()
df2[~filt2].count()
df2.drop(index=df2[~filt2].index, inplace=True)
df2

             이름  국어  영어  수학   합계
번호
1       Eadmund  56  92  60  208
3     Appolonia  77  52  81  210
5        Dallis  97  57  76  230
6      Mitchell  81  95  30  206
8           Rik  80  93  31  204
13       Ardene  91  97  33  221
14      Sibylle  82  81  38  201
17        Alric  68  96  76  240
21    Evangelia  51  71  83  205
22         Abbe  72  65  86  223
27       Gordan  90  31  90  211
29      Timoteo  77  94  67  238
32       Hamnet  95  55  65  215
33     Robinson  55  83  70  208
34       Nollie  84  89  78  251
39          Ban  82  94  80  256
43         Dale  91  96  55  242
44     Lisabeth  78  79  52  209
47       Perkin  82  73  62  217
51    Madeleine  86  55  78  219
52         Buck  93  71  75  239
54          Ula  80  59  85  224
56        Valle  68  83  52  203
57        Grier  64  75  68  207
58      Diahann  90  57  78  225
60      Malynda  57  79  72  208
62        Sheba  88  90  67  245
65         Kiri  64  83  68  215
67     Filberto  60  76  78  214
70        Gilda  71  43  89  203
73        Moise  90  83  65  238
77        Lorna  99  98  86  283
81       Yancey  87  92  66  245
84          Ola  84  77  77  238
90   Bartholemy  70  61  73  204
93        Kiele  68  99  62  229
96         Luke  91  63  59  213
97         Nada  60  89  55  204
98        Fiona  97  95  84  276
99         Leif  96  84  34  214
100    Jonathan  84  63  80  227