In [24]:
import pandas as pd
df = pd.read_excel('file1/scores1.xlsx', index_col='지원번호')
df['합계'] = df['국어'] + df['영어'] + df['수학'] + df['과학'] + df['사회']
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  455
2번    강태원   구로고  184   40   35   50  55  25        Java  205
3번    강호림   구로고  168   80   75   70  80  75  Javascript  380
4번    김수찬   구로고  187   40   60   70  75  80         NaN  325
5번    김재욱   구로고  188   15   20   10  35  10         NaN   90
6번    박동현  디지털고  202   80  100   95  85  80           C  440
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  240
8번    승근열  디지털고  190  100   85   90  95  95          C#  465

In [25]:
# def lowChange(s):
#     if pd.notnull(s):
#         return str(s).lower()
#     return '없음'

# df['SW특기'] = df['SW특기'].apply(lowChange)
# df

def add5(row):
    # row['SW특기']가 null이 아니면 합계에 5를 더함, 아니면 기존 합계 유지
    if pd.notnull(row['SW특기']):
        return row['합계'] + 5
    return row['합계']


# axis=1을 유지하여 각 행별로 함수 적용
df['합계'] = df.apply(add5, axis=1)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  460
2번    강태원   구로고  184   40   35   50  55  25        Java  210
3번    강호림   구로고  168   80   75   70  80  75  Javascript  385
4번    김수찬   구로고  187   40   60   70  75  80         NaN  325
5번    김재욱   구로고  188   15   20   10  35  10         NaN   90
6번    박동현  디지털고  202   80  100   95  85  80           C  445
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  245
8번    승근열  디지털고  190  100   85   90  95  95          C#  470