In [31]:
import pandas as pd
df = pd.read_excel('file1/scores1.xlsx', index_col='지원번호')
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python
2번    강태원   구로고  184   40   35   50  55  25        Java
3번    강호림   구로고  168   80   75   70  80  75  Javascript
4번    김수찬   구로고  187   40   60   70  75  80         NaN
5번    김재욱   구로고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [37]:
import random

df['요일'] = 0

for i in range(8):
    df.loc[df.index[i], '요일'] = random.randint(0, 6)


def d_change(dx):
    if dx == 1:
        return '월'
    elif dx == 2:
        return '화'
    elif dx == 3:
        return '수'
    elif dx == 4:
        return '목'
    elif dx == 5:
        return '금'
    elif dx == 6:
        return '토'
    else:
        return '일'

df['요일'] = df['요일'].apply(d_change)
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기 요일
지원번호
1번    강나래   구로고  197   90   85  100  95  85      Python  토
2번    강태원   구로고  184   40   35   50  55  25        Java  목
3번    강호림   구로고  168   80   75   70  80  75  Javascript  화
4번    김수찬   구로고  187   40   60   70  75  80         NaN  금
5번    김재욱   구로고  188   15   20   10  35  10         NaN  금
6번    박동현  디지털고  202   80  100   95  85  80           C  수
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON  토
8번    승근열  디지털고  190  100   85   90  95  95          C#  목