In [63]:
import pandas as pd
df = pd.read_excel('file1/students.xlsx', index_col='번호')
df

            이름    학교  학년    키  국어  영어  수학    SW특기
번호
1      Eadmund   신림고   2  171  56  92  60       c
2       Kirbee   구로고   1  199  53  10  45       C
3    Appolonia   구로고   3  193  77  52  81       C
4        Avery   구로고   2  187  59  35  43       C
5       Dallis  디지털고   1  209  97  57  76       C
..         ...   ...  ..  ...  ..  ..  ..     ...
96        Luke   신림고   3  187  91  63  59  Python
97        Nada   구로고   3  170  60  89  55  PYTHON
98       Fiona   신림고   1  200  97  95  84       C
99        Leif   구로고   2  192  96  84  34  PYTHON
100   Jonathan  디지털고   2  195  84  63  80    JAVA

[100 rows x 8 columns]

In [64]:
df['합계'] = df['국어'] + df['영어'] + df['수학']
df['평균'] = df['합계'] / 3
df['결과'] = '불합격'
df.loc[df['평균'] >= 70, '결과'] = '합격'
filt1 = df['결과'] == '합격'
df.value_counts('결과')
# df.sort_values(by='평균', ascending=False, inplace=True)
# df.drop(df[~filt1].index, inplace=True)
df

            이름    학교  학년    키  국어  영어  수학    SW특기   합계         평균   결과
번호
1      Eadmund   신림고   2  171  56  92  60       c  208  69.333333  불합격
2       Kirbee   구로고   1  199  53  10  45       C  108  36.000000  불합격
3    Appolonia   구로고   3  193  77  52  81       C  210  70.000000   합격
4        Avery   구로고   2  187  59  35  43       C  137  45.666667  불합격
5       Dallis  디지털고   1  209  97  57  76       C  230  76.666667   합격
..         ...   ...  ..  ...  ..  ..  ..     ...  ...        ...  ...
96        Luke   신림고   3  187  91  63  59  Python  213  71.000000   합격
97        Nada   구로고   3  170  60  89  55  PYTHON  204  68.000000  불합격
98       Fiona   신림고   1  200  97  95  84       C  276  92.000000   합격
99        Leif   구로고   2  192  96  84  34  PYTHON  214  71.333333   합격
100   Jonathan  디지털고   2  195  84  63  80    JAVA  227  75.666667   합격

[100 rows x 11 columns]

In [70]:
# df2 = df[['이름', '평균', '결과']]
# df2
df.columns
cols = list(df.columns)
# cols        # 결과값 ['이름', '학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계', '평균', '결과']
cols[-2:]      # 결과값 ['평균', '결과']
cols[0]        # 결과값 ['이름']   
cols[1:-2]     # 결과값은 ['학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계']

cols1 = [cols[0]] + cols[-2:] + cols[1:-2]
# cols1       # 결과값은 ['이름', '평균', '결과', '학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계']
df = df[cols1]
df

            이름         평균   결과    학교  학년    키  국어  영어  수학    SW특기   합계
번호
1      Eadmund  69.333333  불합격   신림고   2  171  56  92  60       c  208
2       Kirbee  36.000000  불합격   구로고   1  199  53  10  45       C  108
3    Appolonia  70.000000   합격   구로고   3  193  77  52  81       C  210
4        Avery  45.666667  불합격   구로고   2  187  59  35  43       C  137
5       Dallis  76.666667   합격  디지털고   1  209  97  57  76       C  230
..         ...        ...  ...   ...  ..  ...  ..  ..  ..     ...  ...
96        Luke  71.000000   합격   신림고   3  187  91  63  59  Python  213
97        Nada  68.000000  불합격   구로고   3  170  60  89  55  PYTHON  204
98       Fiona  92.000000   합격   신림고   1  200  97  95  84       C  276
99        Leif  71.333333   합격   구로고   2  192  96  84  34  PYTHON  214
100   Jonathan  75.666667   합격  디지털고   2  195  84  63  80    JAVA  227

[100 rows x 11 columns]