In [77]:
import pandas as pd

data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}

df = pd.DataFrame(data)
df.info()
df

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   영화      8 non-null      str
 1   개봉 연도   8 non-null      int64
 2   관객 수    8 non-null      int64
 3   평점      8 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 388.0 bytes

          영화  개봉 연도  관객 수    평점
0         명량   2014  1761  8.88
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
3       국제시장   2014  1426  9.16
4         괴물   2006  1301  8.62
5        도둑들   2012  1298  7.64
6    7번방의 선물   2013  1281  8.83
7         암살   2015  1270  9.10

In [20]:
# df.sort_values('관객 수', ascending=False)
# df['관객 수'] = (df['관객 수']*1000).apply(lambda x: f'{x:,}')
# df['관객 수'] = (df['관객 수']*1000).map('{:,}'.format)
# df.head(5)
# df

In [78]:
# df.sort_values('개봉 연도', ascending=True)
# df.sort_values('개봉 연도', ascending=False)

# df['평점'].astype(str) + '점'
# df

# filt1 = (df['평점'] >= 9)
# filt1 = (df['평점'] >= (df['평점'].mean()))
# df.drop(df[~filt1].index, inplace=True)
filt2 = (df['개봉 연도']>=2015)
df.drop(df[~filt2].index, inplace=True)
df

          영화  개봉 연도  관객 수    평점
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
7         암살   2015  1270  9.10