## Save

In [2]:
import pandas as pd

In [3]:
data = {
    '이름' : ['강나래', '강태원', '강호림', '김수찬', '김재욱', '박동현', '박혜정', '송근열'],
    '학교' : ['신림고', '신림고', '신림고', '신림고', '신림고', '디지털고', '디지털고', '디지털고'],
    '신장' : [197, 184, 168, 187, 188, 202, 188, 190],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기' : ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}
df = pd.DataFrame(data, index = ['1번', '2번', '3번', '4번', '5번', '6번', '7번', '8번'])
df.index.rename("지원번호", inplace=True)
df

       이름    학교   신장   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80
5번    김재욱   신림고  188   15   20   10  35  10
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    송근열  디지털고  190  100   85   90  95  95          C#

### 파일 저장 : csv, txt, xlsx (DB프로그램과 호환)

In [ ]:
# csv
df.to_csv('file01/score.csv', encoding='utf-8-sig') #sig는 엑셀에서 문제없이 열리게 하기 위함

In [ ]:
# txt
# df.to_csv('file01/score.txt')
df.to_csv('file01/score2.txt', sep='\t') #sep는 구분자 지정

In [11]:
# xlsx
df.to_excel('file01/score.xlsx')

### 파일 읽기 : csv, txt, xlsx

In [13]:
df = pd.read_csv('file01/score.csv')
df

  지원번호   이름    학교   신장   국어   영어   수학  과학  사회        SW특기
0   1번  강나래   신림고  197   90   85  100  95  85      Python
1   2번  강태원   신림고  184   40   35   50  55  25        Java
2   3번  강호림   신림고  168   80   75   70  80  75  Javascript
3   4번  김수찬   신림고  187   40   60   70  75  80         NaN
4   5번  김재욱   신림고  188   15   20   10  35  10         NaN
5   6번  박동현  디지털고  202   80  100   95  85  80           C
6   7번  박혜정  디지털고  188   55   65   45  40  35      PYTHON
7   8번  송근열  디지털고  190  100   85   90  95  95          C#

In [15]:
df = pd.read_csv('file01/score.csv', skiprows=1) # 첫번째 행을 건너뛰고 읽기
# df = pd.read_csv('file01/score.csv', skiprows=[1,3,5]) #1,3,5번째 행 건너뛰고 읽기
df

   1번  강나래   신림고  197   90   85  100  95  85.1      Python
0  2번  강태원   신림고  184   40   35   50  55    25        Java
1  3번  강호림   신림고  168   80   75   70  80    75  Javascript
2  4번  김수찬   신림고  187   40   60   70  75    80         NaN
3  5번  김재욱   신림고  188   15   20   10  35    10         NaN
4  6번  박동현  디지털고  202   80  100   95  85    80           C
5  7번  박혜정  디지털고  188   55   65   45  40    35      PYTHON
6  8번  송근열  디지털고  190  100   85   90  95    95          C#

In [8]:
# nrows : 읽을 행의 수 지정
import pandas as pd
df = pd.read_csv('file01/score.csv',  skiprows=1, nrows=4) # 4개의 행만 읽기
df

   1번  강나래  신림고  197  90  85  100  95  85.1      Python
0  2번  강태원  신림고  184  40  35   50  55    25        Java
1  3번  강호림  신림고  168  80  75   70  80    75  Javascript
2  4번  김수찬  신림고  187  40  60   70  75    80         NaN
3  5번  김재욱  신림고  188  15  20   10  35    10         NaN

In [13]:
df = pd.read_csv('file01/2608kor_2.csv')
df

,행정구역,2026년08월_총인구수,2026년08월_세대수,2026년08월_세대당 인구,2026년08월_남자 인구수,2026년08월_여자 인구수,2026년08월_남여 비율
0,전국 (1000000000),"51,084,159","24,505,258",2.08,"25,412,088","25,672,071",0.99
1,서울특별시 (1100000000),"9,281,625","4,525,061",2.05,"4,466,290","4,815,335",0.93
2,전남광주통합특별시 (1200000000),"3,155,803","1,579,291",2.00,"1,578,180","1,577,623",1.00
3,부산광역시 (2600000000),"3,229,467","1,583,256",2.04,"1,568,318","1,661,149",0.94
4,대구광역시 (2700000000),"2,346,277","1,123,265",2.09,"1,148,130","1,198,147",0.96
5,인천광역시 (2800000000),"3,066,185","1,418,345",2.16,"1,530,650","1,535,535",1.00
6,대전광역시 (3000000000),"1,442,838","706,437",2.04,"718,413","724,425",0.99
7,울산광역시 (3100000000),"1,086,373","502,387",2.16,"560,121","526,252",1.06
8,세종특별자치시 (3600000000),"390,738","165,930",2.35,"194,589","196,149",0.99
9,경기도 (4100000000),"13,773,918","6,189,087",2.23,"6,914,277","6,859,641",1.01
10,강원특별자치도 (5100000000),"1,506,662","775,882",1.94,"757,981","748,681",1.01
11,충청북도 (4300000000),"1,601,367","808,665",1.98,"816,717","784,650",1.04
12,충청남도 (4400000000),"2,138,938","1,072,860",1.99,"1,098,834","1,040,104",1.06
13,전북특별자치도 (5200000000),"1,716,965","874,337",1.96,"855,796","861,169",0.99
14,경상북도 (4700000000),"2,492,677","1,303,782",1.91,"1,262,786","1,229,891",1.03
15,경상남도 (4800000000),"3,191,645","1,558,906",2.05,"1,609,943","1,581,702",1.02
16,제주특별자치도 (5000000000),"662,681","317,767",2.09,"331,063","331,618",1.00