In [2]:
import pandas as pd

In [3]:
df = pd.read_excel('file01/score.xlsx', index_col='지원번호')
df

       이름    학교   신장   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
2번    강태원   신림고  184   40   35   50  55  25        Java
3번    강호림   신림고  168   80   75   70  80  75  Javascript
4번    김수찬   신림고  187   40   60   70  75  80         NaN
5번    김재욱   신림고  188   15   20   10  35  10         NaN
6번    박동현  디지털고  202   80  100   95  85  80           C
7번    박혜정  디지털고  188   55   65   45  40  35      PYTHON
8번    송근열  디지털고  190  100   85   90  95  95          C#

In [6]:
df = pd.read_excel('file01/census2025.xlsx')
df

c:\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,※ 매월 말일자 통계 현황,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73
0,NaN,NaN,2025년01월,NaN,NaN,NaN,NaN,NaN,2025년02월,NaN,...,NaN,NaN,NaN,NaN,2025년12월,NaN,NaN,NaN,NaN,NaN
1,행정기관코드,행정기관,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율,총인구수,세대수,...,세대당 인구,남자 인구수,여자 인구수,남여 비율,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율
2,1000000000,전국,"51,207,874","24,124,988",2.12,"25,492,996","25,714,878",0.99,"51,191,817","24,170,531",...,2.10,"25,443,016","25,685,514",0.99,"51,117,378","24,300,087",2.10,"25,436,665","25,680,713",0.99
3,1100000000,서울특별시,"9,330,658","4,482,949",2.08,"4,504,432","4,826,226",0.93,"9,334,828","4,492,425",...,2.07,"4,484,604","4,821,074",0.93,"9,299,548","4,501,031",2.07,"4,481,099","4,818,449",0.93
4,2600000000,부산광역시,"3,263,891","1,569,695",2.08,"1,588,357","1,675,534",0.95,"3,262,337","1,573,020",...,2.06,"1,576,765","1,666,994",0.95,"3,241,600","1,573,996",2.06,"1,575,600","1,666,000",0.95
5,2700000000,대구광역시,"2,363,281","1,104,490",2.14,"1,159,235","1,204,046",0.96,"2,362,578","1,107,127",...,2.12,"1,153,392","1,201,006",0.96,"2,353,032","1,112,508",2.12,"1,152,579","1,200,453",0.96
6,2800000000,인천광역시,"3,023,649","1,375,788",2.20,"1,510,615","1,513,034",1.00,"3,027,854","1,380,110",...,2.18,"1,523,769","1,526,778",1.00,"3,051,961","1,400,788",2.18,"1,524,286","1,527,675",1.00
7,2900000000,광주광역시,"1,407,097","657,716",2.14,"694,532","712,565",0.97,"1,405,226","658,792",...,2.12,"687,996","706,305",0.97,"1,392,013","658,450",2.11,"686,799","705,214",0.97
8,3000000000,대전광역시,"1,438,974","687,941",2.09,"717,162","721,812",0.99,"1,439,809","690,964",...,2.07,"718,512","723,374",0.99,"1,440,729","697,348",2.07,"717,936","722,793",0.99
9,3100000000,울산광역시,"1,097,821","495,677",2.21,"564,893","532,928",1.06,"1,095,778","496,077",...,2.19,"563,204","529,369",1.06,"1,091,948","499,304",2.19,"562,926","529,022",1.06
10,3600000000,세종특별자치시,"390,910","163,404",2.39,"194,470","196,440",0.99,"391,669","164,111",...,2.37,"195,364","197,131",0.99,"391,965","165,220",2.37,"195,107","196,858",0.99
11,4100000000,경기도,"13,699,647","6,062,570",2.26,"6,884,215","6,815,432",1.01,"13,698,657","6,072,106",...,2.24,"6,892,986","6,832,724",1.01,"13,730,135","6,121,301",2.24,"6,894,990","6,835,145",1.01
12,5100000000,강원특별자치도,"1,515,822","764,301",1.98,"762,039","753,783",1.01,"1,513,735","765,316",...,1.96,"758,841","750,110",1.01,"1,508,500","768,900",1.96,"758,575","749,925",1.01
13,4300000000,충청북도,"1,590,666","787,774",2.02,"809,763","780,903",1.04,"1,590,107","789,271",...,2.00,"811,977","781,174",1.04,"1,596,502","797,797",2.00,"813,665","782,837",1.04
14,4400000000,충청남도,"2,135,815","1,052,547",2.03,"1,095,933","1,039,882",1.05,"2,135,340","1,055,137",...,2.01,"1,096,998","1,039,968",1.05,"2,136,753","1,062,282",2.01,"1,097,059","1,039,694",1.06
15,5200000000,전북특별자치도,"1,737,351","864,338",2.01,"865,346","872,005",0.99,"1,735,008","865,541",...,1.99,"859,904","866,056",0.99,"1,724,856","868,116",1.99,"859,325","865,531",0.99
16,4600000000,전라남도,"1,787,592","912,344",1.96,"901,816","885,776",1.02,"1,785,487","913,114",...,1.95,"898,691","880,551",1.02,"1,779,135","913,284",1.95,"898,640","880,495",1.02
17,4700000000,경상북도,"2,528,641","1,291,165",1.96,"1,279,180","1,249,461",1.02,"2,524,067","1,292,811",...,1.94,"1,269,845","1,239,286",1.02,"2,506,526","1,295,685",1.93,"1,268,493","1,238,033",1.02
18,4800000000,경상남도,"3,226,599","1,537,606",2.10,"1,626,214","1,600,385",1.02,"3,221,132","1,539,748",...,2.07,"1,618,023","1,590,837",1.02,"3,207,383","1,548,615",2.07,"1,617,421","1,589,962",1.02
19,5000000000,제주특별자치도,"669,460","314,683",2.13,"334,794","334,666",1.00,"668,205","314,861",...,2.11,"332,145","332,777",1.00,"664,792","315,462",2.11,"332,165","332,627",1.00

In [ ]:
df = pd.read_excel('file01/census2025.xlsx', skiprows=2, index_col='행정기관')
# df.sort_index(inplace=True)
df

c:\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,행정기관코드,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율,총인구수.1,세대수.1,세대당 인구.1,...,세대당 인구.10,남자 인구수.10,여자 인구수.10,남여 비율.10,총인구수.11,세대수.11,세대당 인구.11,남자 인구수.11,여자 인구수.11,남여 비율.11
행정기관,,,,,,,,,,,,,,,,,,,,,
전국,1000000000,"51,207,874","24,124,988",2.12,"25,492,996","25,714,878",0.99,"51,191,817","24,170,531",2.12,...,2.10,"25,443,016","25,685,514",0.99,"51,117,378","24,300,087",2.10,"25,436,665","25,680,713",0.99
서울특별시,1100000000,"9,330,658","4,482,949",2.08,"4,504,432","4,826,226",0.93,"9,334,828","4,492,425",2.08,...,2.07,"4,484,604","4,821,074",0.93,"9,299,548","4,501,031",2.07,"4,481,099","4,818,449",0.93
부산광역시,2600000000,"3,263,891","1,569,695",2.08,"1,588,357","1,675,534",0.95,"3,262,337","1,573,020",2.07,...,2.06,"1,576,765","1,666,994",0.95,"3,241,600","1,573,996",2.06,"1,575,600","1,666,000",0.95
대구광역시,2700000000,"2,363,281","1,104,490",2.14,"1,159,235","1,204,046",0.96,"2,362,578","1,107,127",2.13,...,2.12,"1,153,392","1,201,006",0.96,"2,353,032","1,112,508",2.12,"1,152,579","1,200,453",0.96
인천광역시,2800000000,"3,023,649","1,375,788",2.20,"1,510,615","1,513,034",1.00,"3,027,854","1,380,110",2.19,...,2.18,"1,523,769","1,526,778",1.00,"3,051,961","1,400,788",2.18,"1,524,286","1,527,675",1.00
광주광역시,2900000000,"1,407,097","657,716",2.14,"694,532","712,565",0.97,"1,405,226","658,792",2.13,...,2.12,"687,996","706,305",0.97,"1,392,013","658,450",2.11,"686,799","705,214",0.97
대전광역시,3000000000,"1,438,974","687,941",2.09,"717,162","721,812",0.99,"1,439,809","690,964",2.08,...,2.07,"718,512","723,374",0.99,"1,440,729","697,348",2.07,"717,936","722,793",0.99
울산광역시,3100000000,"1,097,821","495,677",2.21,"564,893","532,928",1.06,"1,095,778","496,077",2.21,...,2.19,"563,204","529,369",1.06,"1,091,948","499,304",2.19,"562,926","529,022",1.06
세종특별자치시,3600000000,"390,910","163,404",2.39,"194,470","196,440",0.99,"391,669","164,111",2.39,...,2.37,"195,364","197,131",0.99,"391,965","165,220",2.37,"195,107","196,858",0.99
경기도,4100000000,"13,699,647","6,062,570",2.26,"6,884,215","6,815,432",1.01,"13,698,657","6,072,106",2.26,...,2.24,"6,892,986","6,832,724",1.01,"13,730,135","6,121,301",2.24,"6,894,990","6,835,145",1.01
강원특별자치도,5100000000,"1,515,822","764,301",1.98,"762,039","753,783",1.01,"1,513,735","765,316",1.98,...,1.96,"758,841","750,110",1.01,"1,508,500","768,900",1.96,"758,575","749,925",1.01
충청북도,4300000000,"1,590,666","787,774",2.02,"809,763","780,903",1.04,"1,590,107","789,271",2.01,...,2.00,"811,977","781,174",1.04,"1,596,502","797,797",2.00,"813,665","782,837",1.04
충청남도,4400000000,"2,135,815","1,052,547",2.03,"1,095,933","1,039,882",1.05,"2,135,340","1,055,137",2.02,...,2.01,"1,096,998","1,039,968",1.05,"2,136,753","1,062,282",2.01,"1,097,059","1,039,694",1.06
전북특별자치도,5200000000,"1,737,351","864,338",2.01,"865,346","872,005",0.99,"1,735,008","865,541",2.00,...,1.99,"859,904","866,056",0.99,"1,724,856","868,116",1.99,"859,325","865,531",0.99
전라남도,4600000000,"1,787,592","912,344",1.96,"901,816","885,776",1.02,"1,785,487","913,114",1.96,...,1.95,"898,691","880,551",1.02,"1,779,135","913,284",1.95,"898,640","880,495",1.02
경상북도,4700000000,"2,528,641","1,291,165",1.96,"1,279,180","1,249,461",1.02,"2,524,067","1,292,811",1.95,...,1.94,"1,269,845","1,239,286",1.02,"2,506,526","1,295,685",1.93,"1,268,493","1,238,033",1.02
경상남도,4800000000,"3,226,599","1,537,606",2.10,"1,626,214","1,600,385",1.02,"3,221,132","1,539,748",2.09,...,2.07,"1,618,023","1,590,837",1.02,"3,207,383","1,548,615",2.07,"1,617,421","1,589,962",1.02
제주특별자치도,5000000000,"669,460","314,683",2.13,"334,794","334,666",1.00,"668,205","314,861",2.12,...,2.11,"332,145","332,777",1.00,"664,792","315,462",2.11,"332,165","332,627",1.00