In [23]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import requests
from bs4 import BeautifulSoup
import time
import os
from dotenv import load_dotenv

import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
import pandas as pd
import numpy as np
import re

In [24]:
df = pd.read_csv('file0/namu_data.cvs')
df2 = df.head(5)
df2

,Unnamed: 0,title,category,content
0,0,틀:화성시의 시설,화성시의 시설둘러보기 틀/건축물/자치단체별,경기도화성시의 시설[ 펼치기 · 접기 ]도시철도병점역어천역광역급행철도동탄역일반철도화...
1,1,사실은 에로했던 동화 빨간 망토,2013년 Windows 게임동인 게임에로게일본 게임판타지 게임RPG 만들기 게임,1. 개요2. 스토리3. 시스템4. 등장인물4.1. 빨간 망토4.2. 미스트4.3....
2,2,네 가지 소원/7회전,네 가지 소원에피소드 가이드,상위 문서:네 가지 소원[ 참가자 ]권혜수길호종박지혜배준성배채운이승은이충명장우준전성...
3,3,레안드로 파레데스,"1994년 출생2011년 데뷔부에노스 아이레스 주 출신 인물AC 키에보베로나/은퇴,...",CA 보카 주니어스2026 시즌 스쿼드1마르체신·2디 로요·3블랑코·4피갈·5파레데...
4,4,홍지원(이름 없는 여자),이름 없는 여자/등장인물한국 드라마 캐릭터,"골프선수에 대한 내용은홍지원(골프선수)문서를, 보디빌더에 대한 내용은홍지원(보디빌더..."

In [25]:
def text_cleaning(text):
    if pd.isna(text):
        return ''
    
    pattern = re.compile(r'[^ 가-힣a-zA-Z0-9]+')
    return pattern.sub('', text)

# df['content']
# text_cleaning(df['content'][0])

df2['title'] = df['title'].apply(lambda x : text_cleaning(x))
df2['category'] = df['category'].apply(lambda x : text_cleaning(x))
df2['content'] = df['content'].apply(lambda x : text_cleaning(x))
df2

,Unnamed: 0,title,category,content
0,0,틀화성시의 시설,화성시의 시설둘러보기 틀건축물자치단체별,경기도화성시의 시설 펼치기 접기 도시철도병점역어천역광역급행철도동탄역일반철도화성시청...
1,1,사실은 에로했던 동화 빨간 망토,2013년 Windows 게임동인 게임에로게일본 게임판타지 게임RPG 만들기 게임,1 개요2 스토리3 시스템4 등장인물41 빨간 망토42 미스트43 빨간 망토의 집4...
2,2,네 가지 소원7회전,네 가지 소원에피소드 가이드,상위 문서네 가지 소원 참가자 권혜수길호종박지혜배준성배채운이승은이충명장우준전성빈한영...
3,3,레안드로 파레데스,1994년 출생2011년 데뷔부에노스 아이레스 주 출신 인물AC 키에보베로나은퇴 이...,CA 보카 주니어스2026 시즌 스쿼드1마르체신2디 로요3블랑코4피갈5파레데스6바탈...
4,4,홍지원이름 없는 여자,이름 없는 여자등장인물한국 드라마 캐릭터,골프선수에 대한 내용은홍지원골프선수문서를 보디빌더에 대한 내용은홍지원보디빌더문서를 ...

In [26]:
titles = " ".join(df2['title'].tolist())
categorys = " ".join(df2['category'])
contents = " ".join(df2['content'])

contents

'경기도화성시의 시설 펼치기  접기 도시철도병점역어천역광역급행철도동탄역일반철도화성시청역향남역고속철도동탄역고속도로경부고속도로서해안고속도로수도권제2순환고속도로평택파주고속도로공원동탄호수공원봉담호수공원종합병원한림대학교동탄성심병원영화관롯데시네마 동탄롯데시네마 향남메가박스 동탄CGV 동탄숙박롤링힐스 호텔베니키아 더에이치 호텔신라스테이 동탄공연장화성아트홀반석아트홀화성예술의전당누림아트홀쇼핑롯데백화점 동탄점메타폴리스몰홈플러스 화성동탄점이마트 동탄점트레이더스 홀세일 클럽 동탄점스타필드마켓 동탄점홈플러스 화성향남점홈플러스 병점점다이소 화성시청점이마트 화성봉담점사찰용주사시설공공도서관행정구역관공서 1 개요2 스토리3 시스템4 등장인물41 빨간 망토42 미스트43 빨간 망토의 집44 숲의 진료소45 이스트 우드 마을46 마녀의 방47 수해48 사막의 마을481 형무소482 성당483 매춘소484 카지노49 감시탑410 통행소411 노스 마을4111 교회4112 찻집412 산의 작은집413 북서쪽 마을414 상인5 아이템6 던전61 늑대의 숲62 동굴63 수해64 폐허의 성65 유적7 마물8 엔딩81 배드 엔딩 A82 배드 엔딩 B83 진 엔딩1개요편집2013년 2월 19일에 발매RPG Maker VX Ace로 제작된 RPG 게임이다 딱 봐도 알겠지만 동화빨간 망토의 이야기를 주제로 했다 한국어 번역이 되어 있다한국에서는 뉴리키라는 유저가 이 게임을 리뷰하면서 널리 알려졌다1장르가야겜이지만 유튜브에도 영상이 돌아다닌다22스토리편집빨간 망토는 엄마와 할머니와 함께 평화롭게 살고 있었다 예전에는 여동생인 미스트도 같이 살고 있었지만 미스트는 고치기 어려운 병에 걸려서 작은 집에서 따로 살고 있다이 병은 사람에게 감염되는 병이라 약을 처방해 주기 위해 간병을 갔을 때만 볼 수 있었다 이에 빨간 망토는 친한 의사에게 미스트의 약을 받고 나서 의사에게 미스트의 병을 고칠 수 있다는 예인의 소문을 듣는다 미스트의 병을 고칠 수 있다는 말에 솔깃한 빨간 망토는 소문의 예인을 찾아 모험을 시작한다3시스템편집게임을 시작하면 화면 왼쪽에 빨간 망토의 전신 일러스트가 뜬다 과도 아이템으로 옷을 스스로 찢거나 몬스터에게 부딪히면 옷이 조금씩 찢겨진다 총 4단계가 있으며 멀쩡한 상태 치마가 찢어진 상태 상의까지 찢겨진 상태3알몸4이 있다 알몸 상태에서 몬스터에게 부딪힐 시 게임 오버가 된다 옷을 고치려면 반짇고리 아이템을 쓰거나 마을의 건물 안에 있는 옷장을 사용하면 된다 옷 상태에 따라서 NPC의 대사가 바뀌는데 남성 NPC의 경우에는 정상적이지 않은 대사가 많다 물론 정상적인 남성 NPC들도 있다 예를 들면 드워프 남자나 광대전라 상태에서 몬스터에게 부딪혀 게임 오버가 될 시 H신이 나타나고 피임약을 쓰겠냐는 질문이 나타나는데 쓸 경우 그 전 스테이지에서 플레이하게 되고 쓰지 않을 경우 던전 입구로 되돌아간다 플레이어가 그 스테이지를 계속해서 통과하지 못할 시엔 다음 스테이지로 이동하겠냐는 질문이 나타난다 이 질문이 나타났을 때 이동하지 않고 또 당할 시 H신을 보겠냐는 선택지가 나타난다시프트키로 대쉬를 할 수 있으며 대쉬는 몬스터가 있는 스테이지에서는 단 한 번 그리고 몇 초 동안만 할 수 있다5메뉴는 몬스터가 있는 곳에서는 열지 못하며 몬스터가 없는 곳에서만 열 수 있다일부 스테이지에서는 빨간색 오브와 보라색 오브가 있는데 빨간색 오브는 한 번 누르면 대쉬를 한 번 더 쓸 수 있게 해주고 보라색 오브는 몬스터가 있는 스테이지에서도 저장을 할 수 있게 해준다알아두면 유용하게 써먹을 수 있는 버그가 있는데 몬스터가 생성되는 순간에 그 몬스터가 생성되는 정확한 지점에서 가만히 있는다면 피격당하지 않는다 이는 북서쪽 마을의 유적지의 촉수지대를 지나갈 때 유용하게 써먹을 수 있다 고속으로 움직이는 적을 상대할 때 내가 움직이는 순간과 적이 고속으로 이동하는 순간을 맞춰서 적과 빨간 망토를 겹치면 피격당하지 않는다 그 이후 적이 고속으로 이동하는 순간에 맞춰서 한 칸 한 칸 적과 빨간 망토를 겹치며 이동하면 된다 하지만 적이 저속으로 이동할 때 움직이면 피격당한다 돼지인간의 경우 돼지인간이 울 때 고속으로 이동해서 이를 이용할 수 있을 것 같지만 겹치면 계속 울어대므로 소리의 유무로는 판별하기 어렵다 고속모드와 저속모드의 시간간격을 잘 재서 움직이면 된다옷이 다 찢어진 상태에서 매춘부의 혼 아이템을 장착하고 NPC에게 말을 걸면 빨간 망토가매춘을 시도하며 일부 남성 NPC와 성관계를 할 수 있다64등장인물편집41빨간 망토편집주인공 항상 빨간 망토를 쓰고 다닌다7엄마나 할머니에게도 빨간 망토로 불리고 마을 사람들에게도 빨간 망토라고 불린다 그래서 이 캐릭터의 본명은 끝날 때까지 알 수 없다양갈래로 땋아 앞으로 내린금발머리에연두색눈동자를 가지고 있다 나이는 대략 10대 초반에서 10대 중반 정도로 추정된다 중요한 사실은 미스트도 가슴이 있다는 것이다 이것까지 예상하면 1516살 정도로 예상된다 동생인 미스트의 병을 고쳐주기 위해 동굴 속 마녀를 찾아가고 마녀가 요구하는 재료들을 모으기 위해 고군분투한다 보다 보면 정말 어린 소녀치고 구르고 또 구른다 보는 입장에서 불쌍하다고 생각될 정도이다만드라고라를 얻기 위해 카지노에서 가슴이 만져지거나동충하초를 얻기 위해뒤치기를 당하거나정액을 받아오거나 성수를 얻기 위해 망령들을 성불시키는 등 굉장히 고생한다 빨간 망토의 순결을 지켜주고 싶어도 스토리상 노스 마을 부잣집 아들에게 동충하초를 얻을 때 반드시 범해진다 즉 처녀 클리어는 불가능하다마음씨는 굉장히 착하고 순수한 성격이다 신부가 건넨로자리오는 신부의 언급상 마음이 깨끗한 사람만 볼 수 있다고 언급하거나 자신에게 불놀이를 요구하는 망령에게도 가엾다고 생각하거나 동생을 위해 고군분투까지 하는 모습을 보면 그야말로 날개 없는 천사아직 나이가 어려서인지 남의 말을 쉽게 믿는 성격인 듯하다 이벤트 진행 시 나오는 살찐 의사가 자신의 여동생을강간하는 장면을 목격하고도 의사에게 따졌을 때 의사는 이것도 다 치료다 하는 식으로 대충 넘어가니 그대로 믿어버리는 모습을 보인다 게다가 마을 사람들에게 알몸으로 말을 걸 때 성폭행을 당해도 보통 네 하고 끝낸다42미스트편집빨간 망토의여동생 나이는 대략 14세15세 정도로 추정된다 머리색은 빨간 망토보다 연한 금발 즉 백금발에 가까우며 눈동자 색은 언니와 똑같다 언니와의 사이가 좋은 편이다 본래는 가족들과 함께 살았었지만 늑대남에게 습격당한 이후로 사람의 형상을 한 것을 보면 몸이 달아오른다고 한다8그때 이후로 작은 집에서 따로 살게 되었다고 한다 병에 걸리게 된 자세한 내막은 나오지 않는다병에 걸린 후 진료소의 친한 의사가 약을 조제해 주며 치료를 시작했지만 증상을 완화시키기만 할 뿐 근본적인 치료는 못 되는 듯하다특정 이벤트를 진행할 시 만나는 살찐 의사에게 당하는 H신이 있다 살찐 의사는 치료는커녕 치료를 가장해 성추행만 한다 의사에게 잠버섯을 가져다주면강간에질내사정까지 당한다내성적인 성격인지9살찐 의사의 이벤트를 보면 자신의 고민을 빨간 망토에게 전달하지 못한다배드 엔딩 A나 B를 보면10언니를성적인 의미로 사랑하고 있었다는 걸 알 수 있다43빨간 망토의 집편집빨간 망토의 집 빨간 망토와 미스트를 제외한 빨간 망토의 가족들이 살고 있다 왠지 아빠는 없다엄마빨간 망토와 미스트의 엄마 빨간 망토가 여행을 떠날 때 도움이 될지 모른다며 반짇고리와 피임약을 건네준다할머니빨간 망토와 미스트의 할머니 빨간 망토와 미스트를 지켜줄 부적을 만든다44숲의 진료소편집친한의사빨간 망토와 평소 알고 지내던 친한 의사 늑대의 숲을 지나면 나오는 숲의 진료소에서 병원을 운영하고 있다 그동안 미스트의 약을 조제해주었으나 증상만 완화시키고 근본적인 치료는 되지 않아 때마침 약을 받으러 온 빨간 망토에게 어떤 병이든지 고칠 수 있다는 예인의 정보를 건넨다나중에 살찐 의사가 미스트를 흥분시키려 마구 몸을 만져댔으나 달아오르는 증상이 발현되지 않은 것을 보아 병을 고치지는 못했지만 억제시키는 것만큼은 확실히 했고 또한 미스트가 자기 몸을 만져대는 살찐 의사를 보고 전에 찾아왔던 의사와는 다르다고 언급한 걸 보면 상당히 도덕적인 인물로 보인다45이스트 우드 마을편집가장 초반에 들를 수 있는 작은 마을 빨간 망토와는 안면이 있는 사람들이다바니걸마을에서 일하는 여인 소문의 예인을 삐에로가 알고 있다는 말을 빨간 망토에게 알려준다삐에로마을에서 일하는 삐에로 소문의 예인이 살고 있는 곳의 정보를 빨간 망토에게 알려준다 이 게임에서 등장하는 남성 NPC 중에서도 상당히 도덕적인 NPC 옷이 찢겨진 상태에서 말을 걸 시 옷 빌려줄까라는 말을 한다 매춘부의 혼을 장착하고 말을 걸어도 빨간 망토는 이러지 않는다며 거절하는 매우 도덕적인 행동을 보인다할아버지마을에서 살고 있는 할아버지 꽤나 밝혀서 전라 상태에서 말을 걸 시 가슴 만지게 해주지 않겠냐는 말을 한다 마녀의 요청을 통해 정액을 얻을 때성관계를 맺게 된다 매춘부의 혼을 장착하고 말을 걸어도성관계를 맺고 500골드를 벌 수 있다할머니마을에서 살고 있는 할머니 전라 상태일 때 취미는 아니지라고 물어본다중년남마을의 주민 꽤나 은둔적인 성격인 듯하다 이쪽도 할아버지마냥 꽤 밝힌다 아니 오히려 집안에 있어서인지 전라 상태에서 말을 걸 시 더욱 더 대범하게 행동하는데 나쁜 남자도 있으니까 조심하지 않으면 안 된다면서 정작 자기가 빨간 망토의 몸을 만져댄다 마녀의 요청으로정액을 이 아저씨에게 받게 되면 이후에 말을 걸 때 대사가 변태스럽게 변하고 알몸 상태로 말을 걸면 강간한다 매춘부의 혼을 장착하고 말을 걸면 매춘이 가능하다청년마을의 주민 이 마을에서 삐에로 사냥꾼과 함께 개념적인 남성 윗도리가 찢겨진 상태에서 말을 걸 시 웃옷을 건네주거나 퀘스트로 정액을 달라고 할 때 중년남이나 할아버지에게 부탁할 시 빨간 망토에게 불놀이를 요구하나 이 청년은 그런 걸 요구하지 않고 스스로자위를 하여 건네주는 등 상당히 도덕적이다 매춘부의 혼을 장착할 시엔 결국 성욕을 참지는 못했는지 하긴 하지만 자신이 나쁜 사람이라며 계속 자책하는 모습을 보인다약제사마을의 약제사 사냥꾼을 치료하기 위해 빨간 망토에게 서브 퀘스트를 제공한다사냥꾼마을의 사냥꾼 늑대남을 사냥하다 중상을 입어 깨어나지 못하는 상태 마녀에게 만능약을 받기 전에 특제약재료를 가져 가면 회복한다 이 사냥꾼을 치료시켰느냐 아니냐에 따라 엔딩이 달라진다 매춘부의 혼을 장착할 시 생명의 은인에게 어떻게 그런 걸 요구하냐며 거절하는 도덕적인 모습을 보인다버그가 하나 있는데 사냥꾼을 치료 안 한 상태에서 사냥꾼의 집에서 알몸 상태로 매춘부의 혼을 장착하고 있으면 왠지 멀쩡히 깨어있다46마녀의 방편집소문의 예인인 동굴의 마녀가 살고 있는 방 어째선지 방으로 가는 길은 마물들 천지이다11동굴의마녀동굴 속에서 살고 있는 마녀 일반적인 동화에 나오는 마녀와는 달리 선량한 마녀다 빨간 망토의 부탁으로 만능약을 만들어주는 대신 재료를 모아와달라는 부탁을 한다 재료는만드라고라동충하초정액성수다고양이마녀와 함께 살고 있는 고양이 말을 걸면 아이템을 사거나 팔 수 있다 역시 마녀의 고양이라 그런지 평범한 고양이가 아니다47수해편집이 수해는 굉장히 길이 복잡해 길을 잃지 않으려면 요정이 필요하다고 한다수수께끼의 노인정체불명의 노인 수해에서 길을 잃지 않으려면 요정이 필요하다는 말을 해준다 동쪽의 카지노에서 요정이 팔리고 있다는 정보를 제공한다 전라 상태일 때 오랜만에섰어라고 말한다 하지만 매춘부의 혼을 착용하고 물어볼 때는 거절하는 모습을 보인다 노인 왈 돈으로 성을 해결할수록 영락해버리지48사막의 마을편집동쪽에 있는 마을 이 마을에서 만날 수 있는 병사의 말로는 꽤나 위험한 곳이라고 한다 실제로 플레이하면 굉장히 치안이 나쁜 걸 알 수 있다촌장사막의 마을의 촌장 사막의 마을은 어른의 마을이라며 빨간 망토 같은 소녀가 올 곳이 아니라는 경고를 한다 매춘부의 혼을 장착하고 말을 걸 시에도 촌장인 내가 어떻게 매춘을 하냐며 거절하는 태도를 보인다병사A마을 서쪽을 지키고 있는 병사 이곳은 남자의 로망이 가득한 곳이라며 빨간 망토에게 어울리지 않는 마을이라고 한다 하지만 알몸 상태에서 말을 걸 땐 너한테 딱 어울리는 마을이네라고 한다병사B마을 서쪽을 지키고 있는 병사 빨간 망토에게 난폭한 일을 당하지 않게 주의하라는 경고를 준다관광객A꽤나 나이가 들어보이는 노인 관광객 대사로 보아 관광 이유는매춘인 듯 매춘부의 혼을 장착하고 말을 걸면 매춘이 가능하다관광객B평범한 인상의 남성 관광객A와 관광 목적은 같은 듯 현재 돈을 다 써서 우울해 있다 매춘행위를 했을 시에돈은 나중에 준다고 한다무용수마을 북쪽에서 무용을 하고 있는 여성 빨간 망토에게 아직 이 마을에 오긴 이른 거 같다고 말하지만 전라 상태에서 말을 걸 시 너도 경쟁자구나 강력한 라이벌이 되겠어라고 한다 매춘부의 혼을 장착했을 때는 나도 동업자인데라고 말한다산적길거리에 쓰러져 있는 산적 배부른 모양이다뚱뚱한 여자남친이 마을에 돌아오지 않았다며 불만을 품고 있는 여자 전라 상태로 말을 걸면 설마 네가 내 남친을이라고 말한다음흉한 남자 뚱뚱한 남자마을 북동쪽에서 쓰러진 여자를 보고 있는 남성들 멀쩡한 상태에서 말을 걸 시 여자를 걱정하는 말을 하는 것처럼 보이나 전라 상태에서 말을 걸 시 하는 말로 보아 범인들은 이놈들인 듯 매춘부의 혼을 장착하고 음흉한 남자에게 말을 걸면 이미 사정해버렸다고 해서 거절하며 뚱뚱한 남자는 매춘이 가능하다지적인 여성마을 북동쪽 구석에 쓰러져 있는 여성 전신에정액이 뿌려져 있다고 하는 걸로 보아 아마강간당한 듯병사C마을 동쪽을 지키고 있는 병사 마을에 너무 오래 머물러 있지 말라는 말을 한다병사D마을 동쪽을 지키고 있는 병사 상당히 과묵한 성격인 듯하며 매춘부의 혼을 장착하고 말을 걸 시에 하는 대사로 보아 매춘부들에게 질린 모양음침한 남자 건장한 남자 뚱뚱한 소년 할아버지마을 남서쪽 구석에서 여성을 습격해성폭행을 하는 놈들 빨간 망토가 이들 사이를 지나갈 시12성폭행을 당하며 전라 상태가 되고 맵 중앙에서 깨어나게 된다481형무소편집포획한 위험생물이나 범죄자를 감금하고 있는 곳이지만 실상은 회상방이다 마물에게 당해 게임 오버될 시 나오는 CG를 다시 볼 수 있는 곳이다간수A형무소가 어떤 곳인지 설명해 준다간수B늑대의 숲의 위험생물을 관리하는 간수 관리 생물은슬라임 늑대의 숲의늑대 늑대의 숲의 거대꽃간수C동굴의 위험생물을 관리하는 간수 관리 생물은 동굴의 늑대 산적 동굴의고블린간수D수해의 위험생물을 관리하는 간수 관리 생물은 마물사 수해의 거대꽃 수해의 늑대남간수E폐허의 위험생물을 관리하는 간수 관리 생물은 부랑자 폐허의 고블린 폐허의 늑대남간수F유적의 위험생물을 관리하는 간수 관리 생물은미노타우로스촉수 돼지남482성당편집사막의 마을의 성당이지만 안에 들어가 보면 폐허 수준이다 성당으로써의 기능은 전혀 하지 못하는 듯하다방랑자성당 안에서 잠들어 있는 방랑자부랑자A이곳의수녀는 가난한 사람에게는 누구나 다리를 벌린다며 좋아하는 부랑자 알몸인 상태로 말을 걸면 바로 강간당한다 매춘부의 혼을 착용하고 말을 걸면 매춘을 하려던 빨간 망토가 위험함을 직감하고 성당 밖으로 도망쳐나온다부랑자B 수녀불놀이 중인 부랑자와 수녀483매춘소편집더 이상의 자세한 설명은 생략한다접수원의외로 정상적인 여성 잘못 들어왔다면 돌려보내려 하고 손님이 건드리는 걸 말린다 매춘하러 들어오면 저기 앉아 일해도 된다며 자리를 내준다손님A뚱뚱한로리콘남자 전라 상태로 말을 걸면 남자가 빨간 망토를 덮치려다 접수원이 그 아이는 신참이라며 제지하기에 매춘부의 혼을 착용해야 매춘이 가능하다손님B성구매가 처음이라 기대하는 손님 매춘이 가능하다손님C매춘하려 말을 걸면 좀 더거유가 취향이라며 거절한다손님D할아버지인 손님 손녀뻘인 빨간 망토가 있는 걸 불편해한다 매춘을 하려 해도 손녀가 생각난다며 거절한다손님E새로 온 아가씨인지 묻는다 매춘을 하려 하면 이미 여자를 지명했다며 거절한다손님F대기 중인 손님 매춘이 가능하다484카지노편집스토리상 요정을 얻기 위해 꼭 들러야 하는 곳 가능한 게임은포커13회원제로 운영되어 코인 획득에도 걸맞은 지위가 필요하다 코인은 경품으로 바꿀 수 있다뚱뚱한 남자A어째선지 알몸인 남자 당연히 사병에게 끌려간다 매춘부의 혼을 착용하고 말을 걸면 지금 상태로는 안된다며 거절한다사병A B뚱뚱한 남자를 구속하고 있는 사병들난폭한 사람의외로 난폭하진 않다매춘부의 혼의 정보를 주는데 알몸인 채 만나면 정보료라며 가슴을 만진다 매춘부의 혼으로 매춘이 가능하다부랑자도박에 쓰는 코인에 집착하며 코인을 찾아다닌다 당연히 코인 안 쓰는 데에도 집착하는 구두쇠 매춘부의 혼을 차고 말을 걸면입으로 핥아주지만꼴랑 1코인만 준다부자빨간 망토에게 500코인에 가슴을 만지게 해달라고 제안한다 카지노에 걸 코인이 있다면야 상관없지만 최초로 코인을 얻기 위해서는 이게 유일한 방법갬블러수해를 빠져나갈 수단인 요정이 돈벌이로도 쓰인다고 말하며 그런 요정의 용도를 거북해한다 매춘부의 혼을 착용하고 말을 걸면 자기 취향이 아니라며 거절한다뚱뚱한 남자B겨우 얻은 요정이라며하악하악댄다 요정에 애착이 강하다 매춘부의 혼을 차고 말을 걸면 요정 사이즈로 줄어들고 찾아오라 한다49감시탑편집폐허의 성의 문을 열기 위해서 들러야 하는 곳강인한 남자폐허의 성의 문을 열기 위해서 말을 걸어야 하는 NPC 자신도 일 때문에 나와 있는 거라서 1000골드를 지급하면 문을 열어주는 것을 도와주겠다는 제의를 한다 매춘부의 혼을 장착한 상태에서 조금 뚱뚱한 남자에게 말을 걸 시 그 남자가 요구하는 걸 만류하는 걸로 보아 도덕성은 있는 인물인 것 같다조금 뚱뚱한 남자1000골드가 부족할 시 이 녀석과 하룻밤을 보낸 뒤 1000골드를 받을 수 있다 강인한 남자에게 존댓말을 사용하는 걸로 보아 후배인 듯하다 하룻밤을 보낸 뒤에 말을 걸 때와 안 보내고 말을 걸 때의 대사가 다르다 이후에도 매춘부의 혼으로 매춘이 가능하다410통행소편집북쪽으로 가기 위해서 지나가야 하는 곳 지나가기 위해 통행료인 1000골드가 필요하다문지기통행소를 지키고 있는 문지기잡상인옆에서 카지노의 물건을 팔면 돈을 비싸게 쳐준다는 상인 돈이 없을 때 이용하면 된다411노스 마을편집통행소를 지나 북쪽에 위치한 마을 꽤나 추운 곳이라고 한다촌장노스 마을의 촌장 동충하초의 정보를 준다 매춘부의 혼을 차고 말을 걸면 촌장으로서의 위엄 때문에 안된다고 거절한다설국경비원노스 마을의 경비원 매춘부의 혼을 차고 말을 걸면 지금 돈이 없다 하며 100G만 낼 수 있냐고 묻고 이에 동의하면 매춘한다마을의 여성노스 마을 병원의 의사에 대해 경고하며 여자는 특히 조심하라 이른다마을의 아저씨찻집의 커피를 명물로 여기는 아저씨 빨간 망토의 옷이 찢어져 있으면 옷을 무료로 고쳐준다 만약 알몸이면 그런 거 없고성폭행을 하는인간 말종 매춘부의 혼을 차고 말을 걸면 매춘이 가능하다마을의 아주머니마을 찻집 단골인 남편이 따라들어가도 없다며 이상해한다 다른 남자들도 찻집에 가면 좀처럼 나오지 않는다고 덧붙인다견습 수도사마을의 견습 수도사 매춘부의 혼을 차고 말을 걸면 빨간 망토를 사면서도이건성교가 아니라며 부정한다드워프방문했던 여행지 중 이곳을 가장 마음에 들어하는 드워프 호탕한 성격에 몇 안 되는 정상인이다 찢어진 옷도 고쳐주고 매춘을 시도해도 오히려 빨간 망토에게 함부로 몸을 팔면 안 된다고 충고해 준다음흉한 아저씨마을 북동쪽 구석에서 불행해보이는 아가씨를 엿보고 있는 사람 매춘부의 혼으로 매춘이 가능하다불행해보이는 아가씨50G에성냥을 파는 아가씨사도 쓸모없다 음흉한 아저씨 왈 몰래매춘도 하고 있다고마을 노인마을의 노인 매춘소에 자주 가는 모양이다 전라 상태에서 말을 걸면 침대로 가자고 하며 이에 동의하면 강간한다 매춘부의 혼을 차고 말을 걸면 손녀가 지갑을 압수해서 못한다고 거절한다마을 아가씨마을 노인의 손녀 빨간 망토에게 원하는 걸 찾으면 좋겠다며 격려해 준다살찐 의사노스 마을의 유일한 의사지만 굉장한 변태라서 마을 여성들이 꺼리는 듯 말을 걸 시 미스트의 병에 관해 상담을 할 수 있는데 선택지가 상담한다와 상담 안 한다가 있다 상담한다를 선택 시 자신이라면 미스트의 병을 고칠 수도 있겠다면서 동생에게 안내해달라고 한다 하지만 실상은 병을 고치긴커녕 치료를 가장한 성추행만 하는 놈이다 즉 안내 시엔 미스트의 H신을 볼 수 있다 이 이벤트 이후엔 이스트 우드 마을 남동쪽 집에 거주하며14전라 상태에서 말을 걸면 빨간 망토도 강간한다 그리고 카지노에서 5천 코인으로 얻을 수 있는 잠버섯을 가져다달라는 부탁을 하는데 만약 가져갈 시엔 성희롱으로 모자라잠버섯으로 재워진 미스트를 덮친다이 이벤트를 마치고 이 의사에게 찾아갈 시 빨간 망토가 그 광경에 관해 항의하지만 이것도 진료의 일부라며 어영부영 넘어간다 그야말로인간 말종15부호노스 마을의 제일 가는 부자 매춘부의 혼을 착용하고 말을 걸 시 아내가 있으니까라고 거절하는 걸 보아 자기 아들과는 달리 도덕적인 남성이다귀부인부호의 아내 전라 상태에서 말을 걸 시 아들이 피해를 줬다며 1000골드를 건네준다 매춘부의 혼을 착용하고 말을 걸 시 어머 마침 잘 됐네 우리 아들 시중 좀 들어줄래라고 권유한다도련님부호와 귀부인의 아들 뚱뚱한 외모이며 살찐 의사와 맞먹는 변태다 멀쩡한 상태에서 말을 걸 시 냅다 옷을 찢어버리거나 동충하초를 찾을 시 빨간 망토를 뒤치기하고선 어영부영 넘어가려는 추태를 보인다 이 NPC에게 매춘 행위를 할 시 저택 지하에 감금되어 게임 오버가 된다 이 NPC에게 매춘으로 돈을 벌려면 오히려 매춘부의 혼을 해제해놓아야 하며 한 번 할 때마다 100골드를 준다 물론 말이 매춘이지 실상은 강간 후 입막음으로 돈을 쥐어주는 것이니 이런 식으로 범한 여자가 한둘이 아닌 듯병사A마을의 북쪽을 지키고 있는 병사 귀여운 아가씨라면 대환영이라는 말을 한다 병사 중에서 가장 성욕이 많아 빨간 망토의 옷 상태에 따라 말이 달라진다병사B마을의 북쪽을 지키고 있는 병사 노스 마을에 관한 간단한 소개를 해준다병사C마을의 남쪽을 지키고 있는 병사 추운 곳에서 근무하지만 추위엔 약한 듯하다병사D마을의 남쪽을 지키고 있는 병사 노스 마을에 관한 간단한 소개를 해준다4111교회편집노스 마을의 교회 작중 도덕적인 사람들의 집합소이다신부노스 마을의 신부수녀노스 마을의 수녀 빨간 망토의 옷이 찢겨질 시 누가 이렇게 만들었냐며 분노하는 모습을 보인다 반면 매춘부의 혼을 장착하고 말을 걸 시 빨간 망토에게 천벌이 내릴 거라는 말을 한다여행자교회는 마음이 안정되는 곳이라고 생각하는 여행자 옷이 찢긴 상태에서 말을 걸 시 걱정하는 모습을 보인다여성눈을 감고 진지하게 기도하고 있는 여성소녀교회에 있는 소녀청년교회에서 기도 중인 청년 옷이 가슴까지 찢긴 상태에서 말을 걸 땐 부끄러워 하지만 알몸 상태에서 말을 걸 땐 환멸스러운 표정을 짓는다유복한 소년 메이드교회에 처음 방문한 듯한 유복한 집안의 소년과 그의 시중을 드는 메이드 치마가 찢긴 상태에서 메이드에게 말을 걸 시 옷을 한 단계 고칠 수 있다청초한 소녀이름은 로자리 눈물을 흘리며 기도하고 있는 소녀 북서쪽의 마을에 있는 청년 망령이 찾고 있던 애인 이 퀘스트를 완료 후 말을 걸면 예전에는 고마웠습니다라는 말을 한다4112찻집편집노스 마을의 명물 찻집 겉으로는 평범한 찻집으로 보이나 실상은 매춘소이다점주 옆에 어떤 공고지가 있는데 이걸 확인해 보면 1시간에 2000골드를 주겠다고 한다 확인 후 점주에게 말을 걸면 매춘 행위로 H신이 나온 뒤 2000골드를 받을 수 있다 단 3번만 할 수 있다이곳에서 알몸 상태로 매춘부의 혼을 장착하고 있으면 어떤 병사가 다가와 부인들에게 매춘하러 돌아다니는 여자가 있다고 통보받았다며 붙잡혀서 병사와 주부들에게 한참 동안 설교를 듣고 쫓겨난다점주찻집의 점주 옆에 있는 게시물을 본 후 말을 걸면 2000골드를 주겠다고 하면서 선택지를 주고 수락 시 매춘소에 데려간다여행자A찻집의 커피가 훈훈해진다며 칭찬을 하는 여행자여행자B찻집의 손님 남쪽에서 자라서 설국이 힘들다고 한다 옷이 가슴까지 찢겨졌을 때 말을 걸 시 부끄러워하는 모습을 보인다강인한 남자찻집의 손님 호탕한 성격 알몸 상태에서 말을 걸 때 그렇고 그런 사람이냐며 묻는다이국의 여성꽤나 먼 데서 온 듯한 여성이국의 남성커피라는 것도 괜찮군이란 대사를 하는 걸로 보아 커피를 처음 마셔본 듯마을 아저씨빨간 망토가 왠지 기분 나쁜 눈을 가지고 있다고 한 남성 치마가 찢긴 상태에서 차를 같이 마시자고 제안할 땐 승낙 시 은근슬쩍 허벅지를 쓰다듬는다 가슴까지 찢겨진 상태에서 말을 걸면 안쪽 방에 가자는 요구를 한다 승낙 시 가슴을 만진다 알몸 상태에서 말을 걸고 선택지에서 승낙을 선택하면 성폭행을 한다할아버지 할머니온화한 성격의 노부부 옷이 찢긴 상태에서 말을 걸 시 옷을 고쳐준다음유시인찻집에서 리퀘스트를 받는 음유시인 옷이 찢긴 상태에서 말을 걸면 빨리 옷을 고치는 게 좋다고 충고한다 상냥한 사람들도 많지만 그 반대도 있다고베테랑 점원찻집 안 매춘소에서 일할 시 만나는 여성 베테랑이라고 대놓고 적혀있다기분 나쁜오타쿠찻집 안 매춘소에서 일할 시 만나는 NPC 도트가 다른 NPC들과는 달리 굉장히 이질적이게 생겼다병사찻집 안에서 알몸 상태로 매춘부의 혼을 장착하고 있을 시 나타난다 등장하면 빨간 망토를 내쫓는다412산의 작은집편집산 사나이산속에서 동충하초를 팔며 생활하던 사나이 현재는 구할 수 없게 되었다며 빨간 망토에게 마지막으로 노스 마을의 부잣집 아들에게 팔았다는 정보를 준다 선량한 사람이며 옷이 찢긴 상태에서 말을 걸 시 이곳도 아직 치안이 나쁜 것 같다거나 매춘부의 혼을 장착하고 말을 걸면 스스로 사양하는 모습을 보인다413북서쪽 마을편집스토리대로 진행하지 않고 바로 가려면 기분 나쁜 곳이라며 진입할 수가 없다 성수를 얻기 위한 퀘스트를 시작하면 갈 수 있는 곳인데 마물의 습격을 받아 마을이 폐허가 되었다고 한다신부북서쪽 마을의 신부 빨간 망토가 마을에 들어올 시 마을은 위험하다며 성당으로 데려온다 여동생의 병을 고치기 위한 재료인 성수를 구하겠다는 사정을 듣고 로자리오를 건네며 모든 망령들을 성불시켜줘야 한다는 말을 한다 사실은 이 신부도 망령 빨간 망토가 모든 망령들을 성불시키며 자신의 한도 풀린 듯하다대장장이 망령대장장이의 망령 애플파이가 먹고 싶다는 부탁을 한다 살아 생전 아내가 가장 잘하는 요리였다고 부탁대로 애플파이를 만들면 가족이 생각났다며 성불한다청년 망령청년의 망령 이름은 에릭 자신의 생전 애인을 찾고 싶다는 부탁을 한다 자신이 필사적으로 막았으니 무사했을 거란 말을 했다 노스 마을 교회에서 청초한 소녀에게 말을 걸면 고맙습니다 정말로 고맙습니다라고 하면서 성불노인 망령노인의 망령 자신의 손자가 보고 싶다는 부탁을 한다 손자의 이름은 마이스 퀘스트는 노스마을 남동쪽 아래에 있는 2번째 묘비에 걸면 성불한다 결국 손자도 이미 마물에게 당한 후였다 명복을 빌어주자쥐 남자알몸 상태인데 본인 말로는 알몸으로 자위하다 마물의 습격을 피하지 못하고 죽었다고 한다 그 빨간 망토도 이 말을 듣고 어이없어하며 이 사람 구제불능이구나라는 생각이 들게 할 정도로 어이없는 이유로 사망한 인물 한 번도 여자와의 만남이 없었다고 빨간 망토와성관계를 요구한다 이후 선택지가 2개 있는데 바라는 대로 해준다와 로자리오로 날려버린다가 있다 로자리오로 날려버리면 빨간 망토가 미안하다며 강제성불 바라는 대로 해준다를 선택하면 이 정도로 자기 만족이 채워졌다며 성불하려는 순간 또 2개의 선택지가 생긴다 하나는 해주는 것 하나는 그냥 그대로 보내주는 것 해주는 것을 선택하면 그대로 H신 후 성불 그런데 해주는 선택 시 하는 말로 보아 아주 나쁘기만 한 인물은 아닌 거 같다 빨간 망토가 해주는 걸 선택했을 때 이제 성불할 수 있을 거 같다면서 말리지만 빨간 망토는 스스로 옷을 벗는다 뭐 쥐 남자 입장에서는 굉장히 행복하게 성불한 것일지도퀘스트를 승낙했을 때 빨간 모자를 따라다니는데 벽을 통과하지 못하는 마물들의 길을 막아 패턴을 부수어 버린다414상인편집반짇고리 반짇고리 DX 피임약을 판매한다 그 외 자신이 가지고 있는 아이템을 팔 수도 있다 돈이 있다면 미리 사두는 것도 좋을 것이다이 상인은 어디에서든지 나타난다 마을은 물론이고 심지어는 마물들에다 산적들까지 거주지로 삼는 동굴 속 요정이 없으면 길을 영원히 헤매게 된다는 수해 부랑자들과 고블린이 나타나는 폐허 심지어 마물이 나타나 폐허가 된 마을의 봉인된 유적 속에서도 나타난다5아이템편집반짇고리옷을 한 단계 고치는 아이템반짇고리 DX반짇고리의 상위 호환 옷을 완전히 고치는 아이템피임약몬스터에게 당해 게임 오버될 시 그 전 스테이지에서 부활하게 해주는 아이템 이 아이템을 쓰지 않을 시 던전 입구로 돌아가 버린다과도반짇고리와 정반대의 아이템으로 스스로 옷을 한 단계씩 찢는 아이템 대신 무한히 쓸 수 있다찢기낫과도의 상위 호환 옷을 한 번에 전부 찢는다 노스 마을의 눈사람에게 말을 걸 시 얻을 수 있다귀환부마녀의 방까지 순간이동할 수 있는 아이템 동굴의 마녀와 만나면 얻을 수 있다특효약 레시피이스트 우드 마을의 약제사에게 말을 걸면 얻을 수 있다 사냥꾼을 치료하기 위한 약재료가 써져 있다 재료는 장수버섯 독버섯 우월초 납월초 검은꿀 이 재료들은 각 던전 인근에 있는 별도의 맵을 클리어해야 얻을 수 있다성냥노스 마을의 불행해보이는 아가씨에게 말을 걸 시 50골드에 사고 얻을 수 있는 아이템 별 쓸모는 없다 사용 시 맵이 붉어지며 빨간 망토가따뜻하다고 한다요정카지노에서 3000코인과 교환할 수 있는 아이템 수해를 지나가기 위해 꼭 필요하다잠버섯카지노에서 5000코인과 교환할 수 있는 아이템 살찐 의사와의 이벤트를 거치고 요구하는 아이템 수면제로 쓰인다는 희귀한 버섯 이 버섯을 가지고 이스트 우드 마을의 살찐 의사에게 갈 시엔매춘부의 혼카지노에서 10000코인과 교환할 수 있는 아이템 카지노의 난폭한 사람 말에 의하면 이것을 가지고 있으면 매춘을 하는 여자가 아니라도 매춘 하고 싶어 견딜 수 없는 기분이 된다고 이것을 장착하고 알몸 상태로 NPC들에게 말을 걸 시 매춘 행위가 가능해진다로자리오북서쪽 마을의 신부가 건넨 아이템 이것을 장착하면 망령을 볼 수 있게 된다 또한 솔라빔으로 망령을 죽일 수 있다부적동굴의 마녀가 약을 완성하고 집에 있는 할머니에게 갈 시 받을 수 있는 부적 진 엔딩과 배드 엔딩 A를 가르는 아이템사과애플파이를 만드는 재료 중 하나 늑대의 숲 위쪽 친한 의사가 있는 길목의 큰나무 밑에 있다 먹을 수 있으나 그러면 늑대의 숲을 다시 클리어해야 한다파이 틀애플파이를 만드는 재료 중 하나 동굴의 마녀가 가지고 있으며 빨간 망토가 요청하면 준다만드라고라미스트의 약을 만드는 재료 중 하나 폐허의 성에서 얻을 수 있다동충하초미스트의 약을 만드는 재료 중 하나 산 사나이가 마지막 하나를 노스 마을의 부잣집 아들에게 팔았고 이 아들에게서 구할 수 있으나 그 대가로 뒷치기를 당한다16정액미스트의 약을 만드는 재료 중 하나 이스트 우드 마을의 남성 NPC 중 하나에게 부탁하면 준다성수미스트의 약을 만드는 재료 중 하나 북서쪽 마을 유적에서 얻을 수 있다6던전편집61늑대의 숲편집늑대가 나오는 숲 북쪽 루트와 동쪽 루트가 있는데 북쪽은 친한 의사의 진료소로 가는 길이고 동쪽은 미스트가 있는 집으로 가는 길이다 등장 마물은 슬라임과 늑대 거대꽃62동굴편집동굴의 마녀를 찾아가기 위해 진입해야 하는 던전 일단 클리어하고 나면 마녀가 귀환서를 건네주고 동굴 입구에 마녀의 방으로 직행하는 입구가 열린다 등장 마물은 늑대와 산적 고블린63수해편집폐허의 성으로 가는 길목에 위치 수해에서는 길을 헤메기 때문에 통과하려면 카지노에서 판매하는 요정을 구입해서 길안내를 받아야 한다 등장 마물은 거대꽃과 마물사 늑대남64폐허의 성편집만드라고라가 있는 아무도 살지 않는 성 동굴의 마녀의 의하면 죄인을 처형하던 집행장이었다고 한다 성문을 열려면 감시탑에 있는 강인한 남자에게 1000 골드를 지급하고 도움을 받아야 한다 등장하는 마물은 부랑자와 고블린 늑대남65유적편집성수를 얻기 위해 북서쪽 마을의 망령들을 전부 성불시켜주면 진입할 수 있는 던전 등장 마물은 미노타우로스와 촉수 돼지남7마물편집슬라임늑대의 숲에서 출현H신은 빨간 망토에게 달라붙고 빨간 망토는 어떻게든 막으려고 하지만 액체인 슬라임을 막지 못하고질내사정을 당한다늑대늑대의 숲과 동굴에서 출현H신은 빨간 망토가 늑대에게 덮쳐져질내사정당한다거대꽃늑대의 숲과 수해에서 출현H신은 늑대의 숲에서는 그냥대딸해 주지만 수해에서는 배에다가 알을 낳는다 공통점은 꽃봉오리로 가슴을 핥는다는 것산적동굴에서 출현H신은 빨간 망토에게질내사정하고 아지트에 데려가서성노예로 쓴다고블린동굴과 폐허에서 출현H신은 빨간 망토에게 더러운 것을 넣는다 그 다음에질내사정한다마물사수해에서 출현H신은 산적이랑 똑같지만 그 다음은 돼지 인간이나 고블린 등을 낳게 하는 것에 쓰인다고 말한다부랑자폐허에서 출현H신은 빨간 망토에게질내사정한다미노타우로스유적에서 출현 성기가 매우 크다촉수유적에서 출현H신은 거대꽃과 비슷하다 늑대남을 제외하면 빨간 망토를 세뇌시킨 유일한 마물 그래서인지 빨간 망토의 대사가 상당히 변태스럽게 변한다돼지남유적에서 출현 잡히면 옷이 전부 벗겨진다 꽤나 피하기 어렵다H신은질내사정후성노예로 만든다늑대남수해와 폐허 최종편에서 출현 등장 시엔 무조건 도망쳐야 한다 수해는 어느 정도 쉽지만 폐허는 속력을 일정하게 유지해야 하고 코너를 잘못 돌면 끝 최종편을 제외하면 잡히고 나서 옷이 전부 벗겨진다 이 게임의 주적으로 미스트가 병에 걸린 이유도 이 녀석 때문 진 엔딩으로 가면 결국 사살된다H신은수간8엔딩편집엔딩은 총 3가지가 있으며 어떤 조건을 충족했느냐에 따라 엔딩이 달라진다 마녀에게 만능약을 얻고 이스트 우드 마을로 가면 청년이 다급하게 늑대남이 미스트의 집으로 갔다고 말해준다이 문서에스포일러가 포함되어 있습니다이 문서가 설명하는 작품이나 인물 등에 대한 줄거리 결말 반전 요소 등을 직간접적으로 포함하고 있습니다81배드 엔딩 A편집언니에게 키스하며이것이나의 세계 미스트조건은 사냥꾼은 치료했으나 할머니에게 부적을 얻지 못했을 때늑대남이 미스트의 집을 습격했지만 사냥꾼이 지켜 미스트는 무사했다 늑대남은 미스트의 집에서 도망치고 사냥꾼은 그 뒤를 쫓는다빨간 망토는 미스트가 무사하냐고 묻고 약을 주려 하지만 아까 늑대남이 밀치고 간 충격으로 약이 바닥에 떨어져 증발해간다 빨간 망토는 놀라며 동굴의 마녀에게 다시 받아온다고 했지만 미스트는 이젠 괜찮다며 그것보단언니를 원한다며빨간 망토에게키스를 한다 병은 아무래도 상관없다며 예전부터 언니를 좋아했다고 하며 여기서 계속 기분 좋게 있자고 한다미스트와의 키스로 감염된 빨간 망토도 동생 미스트에게 성적 매력을 느끼고 화면은 둘의 키스신으로 넘어간다 잠시 후 멀리서 총소리가 울리고 늑대남은 잡힌다 하지만 둘은 그런 건 아무래도 상관없다며 둘이 찐한 사랑을 나눈다해피 엔딩인데즉근친백합엔딩 빨간 망토가 망토를 벗은 유일한 장면이다82배드 엔딩 B편집조건은 사냥꾼을 치료 못했을 때미스트의 집에 갔을 때 빨간 망토가 목격한 것은 늑대남에게 범해지고 있는 미스트였다 타락한 미스트는 빨간 망토에게 키스를 하며 병을 감염시켜 버렸고 여기서 같이 기분 좋게 되자고 한다 빨간 망토도 타락해 늑대남에게 성행위를 요구한다결국 빨간 망토와 미스트는 늑대남에게 타락해 성행위를 요구하는 상태가 되어버린다미스트의 집 밖에서는 청년이 안에는 소녀들이 있다면서 걱정하지만 노인이 이미 늑대남에게 당했다며 늑대남을 당해낼 수 없다고 말한다 노인은 이 마을도 이제 끝장이다 늑대남을 잡을 수 있는 사람이 없다니라며 절망한다그 후 빨간 망토와 미스트를 본 사람은 아무도 없었다고 한다진 엔딩 조건 충족 시 진행되는 늑대남 탈출 이벤트에서 도망치지 못할 시에도 이 엔딩이 나온다 다만 H신 장면만 나온다 뒷부분에 마을 사람들이 절망하는 말은 안 나온다 아마 사냥꾼이 뒤늦게 쫓아와서 늑대남을 처치한 듯하다노인의 언급을 보면 다른 사람이 늑대남을 죽이면 안 되나라는 생각을 하게 하지만 사냥꾼도 늑대와 싸워서 큰 부상을 입었다가 이때서야 겨우 늑대를 사냥한 것을 보면 평소엔 잘 숨어다니는지 잡기 매우 힘든 것으로 보인다83진 엔딩편집조건은 사냥꾼을 치료하고 할머니에게 부적을 받았을 때늑대남이 미스트의 집을 습격했지만 사냥꾼이 지켜 미스트는 무사했다 늑대남은 도망치고 사냥꾼은 그 뒤를 쫓는다빨간 망토는 미스트가 무사하냐고 묻고 약을 주려 하는데 늑대남이 아까 밀친 충격으로 약을 떨어뜨렸다 다행히 약은 무사했고 빨간 망토는 미스트에게 약을 먹인다 효과가 있었는지 미스트는 금세 낫고 빨간 망토는 안도의 한숨을 쉰 순간 늑대남이 미스트의 집을 다시 습격했다 빨간 망토와 미스트는 늑대남에게서 도망치고 사냥꾼이 늑대남을 죽이면서 무사히 살아남는다그 후 빨간 망토와 미스트는 행복하게 살았다고 한다1최초로 올라온 게시물은 티비플 게시글 제목이 영어명인 Red Hood Ring이어서인지 번역된 원문보다 영문으로 많이 알려져 있다 Red Hood Ring이라는 영문은 당연히 오타인데 이는 번역자가 게임을 배포할 때 주로 영어명으로 쓰는데 Red Riding Hood라고 써야 하는 걸 실수로 Red Hood Ring으로 써서 배포해버리면서 10여 년 간 그 제목으로 거의 굳어져 버리게 된 것이다 그때는 빨간 망토의 이름이 Ring인 줄 알았다는 생각을 했다고2물론 유튜브는 검열이 엄격하기 때문에 음부 등이 약간이라도 드러나거나 하는 장면은 모자이크 처리되며 성행위 장면은 당연히 스킵된 채로 게임 클리어와 스토리 진행만 중계한다 즉 나는 게임하는 것만 보여줄테니 만약 H신이 보고 싶다면 네가 직접 해야 한다 같은 느낌3마물에게 당해 찢긴 경우 이 상태에선 우우 가슴이라는 대사가 나온다4마물에게 당해 찢긴 경우 이 상태에선 우우 이제 한계야라고 한다5만약 실수로 대쉬를 썼다면 전의 스테이지로 돌아가 다시 들어오면 쓸 수 있다6근무 중인 병사 NPC에게 이 상태로 말을 건다면 근무 중이라서 나중에라거나 거지에게 하면 1코인을 받는 등 여러 가지 반응이 있다7옷이 다 찢겨져 알몸인 상태에서도 빨간 망토는 쓰고 있다 유일하게 백합 엔딩에서만 망토를 벗는다8여러 정황으로 볼 때 병에 감염된 경우 사람의 형상을 한 것만 봐도 성욕이 강제로 발생하는 것으로 추정된다9빨간 망토의 언급에 의하면 낯을 가린다고 한다10B에서는 강간당하면서 타락한지라 좀 애매하지만 A에서는 자신의 병을 막을 수단이 없어져서인지는 몰라도 언니에게 고백하고 서로 성적으로 맺어지는 백합 엔딩이 있는 걸 보면 확실하다11일단 마녀의 방으로 진입하고 나면 동물 입구에 마녀의 방으로 직행하는 입구가 열린다123x3 칸으로 차있고 모서리 쪽에 한 명씩 서있는데 대놓고 이벤트 생기라고 가운데 칸만 비어있다 보통 마을 지형 같은 것은 생각을 안 하고 지나가기 때문에 처음 플레이하면 한 번쯤은 보게 된다 CG는 없다 이들 옆에서 말을 걸면 별다른 반응은 없다13모바일은 기기 호환 문제로 카드가 다 보이지 않는다14다만 노스 마을 병원에도 어째서인지 계속 있다 여기서 매춘부의 혼을 장착하고 말을 걸면 프로를 범하는 건 질렸고 아마추어가 좋다며 거절한다15이 이벤트를 거치고 엔딩을 볼 시 미스트의 집 앞에 쓰러져 죽어있는 모습으로인과응보를 치른 모습을 볼 수 있다 살펴보면 여기저기 베이고 찢긴 상처가 있다고 하는데 정황상 늑대남에게 당해 죽은 듯16이 이벤트는 피할 수 없기에 빨간 망토의 처녀 클리어는 불가능하다 상위 문서네 가지 소원 참가자 권혜수길호종박지혜배준성배채운이승은이충명장우준전성빈한영우 에피소드 1회전2회전3회전4회전5회전6회전7회전 관련 문서 공개 전 정보참가자에피소드 목록내용 및 진행 결과평가 및 반응여담추측 및 떡밥이 문서에스포일러가 포함되어 있습니다이 문서가 설명하는 작품이나 인물 등에 대한 줄거리 결말 반전 요소 등을 직간접적으로 포함하고 있습니다1 개요2 게임 시작 전3 7회전 체크메이트31 규칙32 게임 진행321 1라운드322 2라운드323 3라운드33 게임 평가4 엔딩1개요편집네 가지 소원의 7회전결승전 내용을 정리한 문서2게임 시작 전편집37회전 체크메이트편집31규칙편집체크메이트는 개성 있는 말들을 이동하여 숨겨진 승리 조건을 달성해야 하는 게임이다게임은 3라운드로 진행하며 두 라운드를 먼저 승리하는 플레이어가 최종 우승한다가로 세로 5칸으로 이뤄진 게임판 위에서 정해진 세 칸 위에 말을 놓고 게임을 시작한다선 플레이어부터 번갈아 가며 차례를 가진다 1라운드의 선 플레이어는 6회전의 두 번째 우승자가 2라운드부터는 직전 라운드의 패자가 결정한다차례의 순서에 비례해 턴 플레이어는 행동해야 하는 횟수가 정해진다 선 1회 후 2회 선 3회 즉 게임이 길어질 수록 한 차례 더 많은 횟수의 행동을 해야 한다제한 시간 또한 1분에서 시작해 10초씩 증가한다행동의 종류는 다음 다섯 가지가 존재한다 말 이동 자신 소유의 말 중 하나를 골라 이동시킨다 다람쥐 배치 아무 빈 칸에 자신의 다람쥐 하나를 배치한다 배치한 다람쥐는 다음 차례부터 이동이 가능하며 이 행동에 한해 1번당 3번의 횟수를 소모한 것으로 간

In [27]:
import os
os.environ["JAVA_HOME"] = r"C:\jdk21"
print(os.environ["JAVA_HOME"])

import jpype
print(jpype.getDefaultJVMPath())

from konlpy.tag import Okt
from collections import Counter

C:\jdk21
C:\jdk21\bin\server\jvm.dll

In [29]:
# text = '나는 당신을 사랑합니다. 감사합니다. 고맙습니다. 당신이 최고입니다.'
# n_tag = Okt()
# nouns = n_tag.nouns(text)
# print(nouns)

from collections import Counter

n_tag = Okt()
nouns = n_tag.nouns(contents)
# print(nouns)
count = Counter(nouns)
count

Counter({'말': 170,
         '것': 138,
         '자신': 106,
         '해주': 105,
         '수': 103,
         '망토': 96,
         '마을': 96,
         '이': 79,
         '손여리': 79,
         '걸': 64,
         '상태': 59,
         '편집': 58,
         '주호': 58,
         '시': 57,
         '때': 56,
         '도영': 55,
         '늑대': 50,
         '미스트': 49,
         '알': 49,
         '위해': 42,
         '홍': 42,
         '집': 40,
         '매춘부': 39,
         '안': 38,
         '혼': 38,
         '데스': 38,
         '그': 37,
         '사람': 36,
         '지원': 36,
         '마야': 36,
         '후': 35,
         '번': 34,
         '남': 34,
         '다시': 33,
         '파레': 33,
         '때문': 32,
         '손': 31,
         '옷': 30,
         '계속': 30,
         '매춘': 30,
         '가야': 30,
         '게임': 29,
         '내': 29,
         '세': 29,
         '행동': 27,
         '도치': 27,
         '마녀': 26,
         '선수': 26,
         '딸': 26,
         '의사': 25,
         '가지': 24,
         '등': 24,
         '하자': 24,
         '약': 23,
         '남자': 23,
         '전': 23,
         '이후': 23,
         '듯': 23,
         '중': 23,
         '거': 23,
         '게': 23,
         '곳': 22,
         '병사': 22,
         '리': 22,
         '아르헨티나': 22,
         '노스': 21,
         '아이템': 21,
         '엔딩': 21,
         '병': 21,
         '부탁': 21,
         '마르': 21,
         '월드컵': 21,
         '자식': 21,
         '동굴': 20,
         '마물': 20,
         '볼': 20,
         '장': 20,
         '생각': 20,
         '아이': 20,
         '위': 20,
         '최': 20,
         '더': 19,
         '알몸': 19,
         '이동': 19,
         '인물': 19,
         '모든': 19,
         '수해': 18,
         '플레이': 18,
         '사냥꾼': 18,
         '일': 17,
         '폐허': 17,
         '살': 17,
         '뒤': 17,
         '대해': 17,
         '문서': 17,
         '수비': 17,
         '곧바로': 17,
         '화': 17,
         '숲': 16,
         '사실': 16,
         '못': 16,
         '거절': 16,
         '건': 16,
         '티': 16,
         '네스': 16,
         '친딸': 16,
         '데리': 16,
         '찻집': 15,
         '다음': 15,
         '상대': 15,
         '망령': 15,
         '치료': 15,
         '하나': 15,
         '데': 15,
         '조건': 15,
         '대한': 15,
         '리가': 15,
         '해성': 15,
         '회장': 15,
         '말년': 15,
         '엄마': 14,
         '칸': 14,
         '아들': 14,
         '마음': 14,
         '돈': 14,
         '코인': 14,
         '라운드': 14,
         '김무열': 14,
         '전라': 13,
         '선택': 13,
         '모습': 13,
         '진행': 13,
         '자기': 13,
         '역시': 13,
         '라며': 13,
         '너': 13,
         '여자': 13,
         '바로': 13,
         '징표': 13,
         '경기': 13,
         '골수': 13,
         '봄': 13,
         '전화': 13,
         '동탄': 12,
         '카지노': 12,
         '대사': 12,
         '경우': 12,
         '정도': 12,
         '요구': 12,
         '재료': 12,
         '성불': 12,
         '즉': 12,
         '골드': 12,
         '오히려': 12,
         '요정': 12,
         '노인': 12,
         '손님': 12,
         '본인': 12,
         '팀': 12,
         '패스': 12,
         '상황': 12,
         '악행': 12,
         '모성애': 12,
         '점': 11,
         '방': 11,
         '시작': 11,
         '남성': 11,
         '순간': 11,
         '소리': 11,
         '가슴': 11,
         '몸': 11,
         '정보': 11,
         '보아': 11,
         '매우': 11,
         '이유': 11,
         '생물': 11,
         '간수': 11,
         '구': 11,
         '개': 11,
         '출현': 11,
         '승리': 11,
         '축구': 11,
         '메시': 11,
         '입양': 11,
         '얘기': 11,
         '지원이': 11,
         '할머니': 10,
         '몬스터': 10,
         '플레이어': 10,
         '시간': 10,
         '성격': 10,
         '이벤트': 10,
         '살찐': 10,
         '나': 10,
         '보고': 10,
         '등장': 10,
         '관리': 10,
         '도': 10,
         '차': 10,
         '마지막': 10,
         '피': 10,
         '포함': 10,
         '간': 10,
         '다람쥐': 10,
         '보카': 10,
         '주니어스': 10,
         '국가대표팀': 10,
         '당신': 10,
         '드라마': 10,
         '경찰': 10,
         '위드': 10,
         '무열': 10,
         '자수': 10,
         '수도': 9,
         '교회': 9,
         '진': 9,
         '강간': 9,
         '장면': 9,
         '가장': 9,
         '를': 9,
         '병원': 9,
         '청년': 9,
         '길': 9,
         '경고': 9,
         '여성': 9,
         '부랑': 9,
         '이상': 9,
         '선': 9,
         '둘': 9,
         '이름': 9,
         '사망': 9,
         '이제': 9,
         '전부': 9,
         '줄': 9,
         '문제': 9,
         '차례': 9,
         '특수': 9,
         '기물': 9,
         '사건': 9,
         '단점': 9,
         '퇴장': 9,
         '날': 9,
         '갑자기': 9,
         '주가': 9,
         '왜': 9,
         '그룹': 9,
         '기억': 9,
         '개요': 8,
         '북서쪽': 8,
         '유적': 8,
         '로': 8,
         '반짇고리': 8,
         '신': 8,
         '스테이지': 8,
         '또': 8,
         '소녀': 8,
         '다만': 8,
         '신부': 8,
         '나중': 8,
         '할아버지': 8,
         '꽤': 8,
         '착용': 8,
         '위험': 8,
         '처음': 8,
         '어디': 8,
         '내용': 8,
         '및': 8,
         '소유': 8,
         '배치': 8,
         '종료': 8,
         '참고': 8,
         '대회': 8,
         '결승전': 8,
         '공격': 8,
         '공': 8,
         '파울': 8,
         '비': 8,
         '향': 8,
         '몰리나': 8,
         '주장': 8,
         '김': 8,
         '구해': 8,
         '보육원': 8,
         '협박': 8,
         '진짜': 8,
         '죄': 8,
         '연락': 8,
         '아버지': 8,
         '역': 7,
         '화성': 7,
         '이스트': 7,
         '우드': 7,
         '매춘소': 7,
         '던전': 7,
         '적': 7,
         '인간': 7,
         '속': 7,
         '동충하초': 7,
         '정액': 7,
         '클리어': 7,
         '습격': 7,
         '버섯': 7,
         '질내사정': 7,
         '사랑': 7,
         '온': 7,
         '또한': 7,
         '도덕': 7,
         '통해': 7,
         '아저씨': 7,
         '퀘스트': 7,
         '정체': 7,
         '북쪽': 7,
         '범인': 7,
         '고블린': 7,
         '잘못': 7,
         '아가씨': 7,
         '차고': 7,
         '다른': 7,
         '부정': 7,
         '우리': 7,
         '확인': 7,
         '기분': 7,
         '심지어': 7,
         '사고': 7,
         '최종': 7,
         '충격': 7,
         '평가': 7,
         '방향': 7,
         '레안드로': 7,
         '코파': 7,
         '키': 7,
         '미드필더': 7,
         '논란': 7,
         '킥': 7,
         '자체': 7,
         '감정': 7,
         '니': 7,
         '아기': 7,
         '치가': 7,
         '이혼': 7,
         '경찰서': 7,
         '회사': 7,
         '라이터': 7,
         '스토리': 6,
         '진료': 6,
         '성당': 6,
         '배드': 6,
         '치기': 6,
         '예인': 6,
         '스스로': 6,
         '의': 6,
         '입구': 6,
         '시엔': 6,
         '동안': 6,
         '돼지': 6,
         '이용': 6,
         '시도': 6,
         '앞': 6,
         '드': 6,
         '불': 6,
         '목격': 6,
         '언니': 6,
         '가족': 6,
         '달라': 6,
         '동쪽': 6,
         '촌장': 6,
         '행위': 6,
         '산적': 6,
         '걱정': 6,
         '꽃': 6,
         '전혀': 6,
         '자리': 6,
         '간다': 6,
         '지금': 6,
         '자주': 6,
         '눈': 6,
         '강제': 6,
         '미리': 6,
         '편': 6,
         '여기': 6,
         '직접': 6,
         '명': 6,
         '상처': 6,
         '두': 6,
         '판': 6,
         '탈리아': 6,
         '라시': 6,
         '오스': 6,
         '로메': 6,
         '감독': 6,
         '아메리카': 6,
         '경력': 6,
         '폭행': 6,
         '태클': 6,
         '싸움': 6,
         '네덜란드': 6,
         '스페인': 6,
         '선언': 6,
         '리오넬': 6,
         '멘디': 6,
         '배우': 6,
         '배종옥': 6,
         '소식': 6,
         '친모': 6,
         '교도소': 6,
         '처': 6,
         '눈치': 6,
         '비서': 6,
         '고속': 5,
         '고속도로': 5,
         '클럽': 5,
         '소': 5,
         '사막': 5,
         '성': 5,
         '소문': 5,
         '오버': 5,
         '사용': 5,
         '동생': 5,
         '성수': 5,
         '범': 5,
         '로자리오': 5,
         '언급': 5,
         '식': 5,
         '성폭행': 5,
         '사이': 5,
         '잠': 5,
         '제외': 5,
         '부적': 5,
         '며': 5,
         '가면': 5,
         '대신': 5,
         '주의': 5,
         '현재': 5,
         '보이': 5,
         '남자에게': 5,
         '설명': 5,
         '거대': 5,
         '수녀': 5,
         '손녀': 5,
         '채': 5,
         '문': 5,
         '조금': 5,
         '옆': 5,
         '동의': 5,
         '아내': 5,
         '누가': 5,
         '여행자': 5,
         '수가': 5,
         '손자': 5,
         '결말': 5,
         '반응': 5,
         '서로': 5,
         '소원': 5,
         '관련': 5,
         '여담': 5,
         '횟수': 5,
         '가격': 5,
         '해당': 5,
         '표기': 5,
         '능력': 5,
         '디': 5,
         '로마': 5,
         '제니트': 5,
         '기록': 5,
         '악역': 5,
         '죽지': 5,
         '분노': 5,
         '표': 5,
         '벤치': 5,
         '비판': 5,
         '탓': 5,
         '제대로': 5,
         '터': 5,
         '피코': 5,
         '몬티': 5,
         '페르': 5,
         '알바': 5,
         '레스': 5,
         '명단': 5,
         '조작': 5,
         '납치': 5,
         '에손': 5,
         '의심': 5,
         '계략': 5,
         '계획': 5,
         '연기': 5,
         '거짓말': 5,
         '비밀': 5,
         '도중': 5,
         '척': 5,
         '설득': 5,
         '용서': 5,
         '홀': 4,
         '통행': 4,
         '산': 4,
         '상인': 4,
         '영상': 4,
         '예전': 4,
         '여동생': 4,
         '감염': 4,
         '단계': 4,
         '피임': 4,
         '질문': 4,
         '대쉬': 4,
         '초': 4,
         '일부': 4,
         '오브': 4,
         '촉수': 4,
         '성관계': 4,
         '나이': 4,
         '추정': 4,
         '부잣집': 4,
         '인지': 4,
         '네': 4,
         '편이': 4,
         '성적': 4,
         '도움': 4,
         '삐': 4,
         '쪽': 4,
         '집안': 4,
         '더욱': 4,
         '변태': 4,
         '고양이': 4,
         '길이': 4,
         '태도': 4,
         '땐': 4,
         '관광객': 4,
         '관광': 4,
         '지적': 4,
         '소년': 4,
         '실상': 4,
         '누구': 4,
         '중인': 4,
         '구매': 4,
         '좀': 4,
         '위치': 4,
         '커피': 4,
         '만약': 4,
         '몰래': 4,
         '상담': 4,
         '안정': 4,
         '눈물': 4,
         '점주': 4,
         '부인': 4,
         '승낙': 4,
         '진입': 4,
         '애플파이': 4,
         '에릭': 4,
         '아무': 4,
         '끝': 4,
         '스포일러': 4,
         '작품': 4,
         '간접': 4,
         '키스': 4,
         '세계': 4,
         '도망': 4,
         '그것': 4,
         '친': 4,
         '다그': 4,
         '가운데': 4,
         '결과': 4,
         '환불': 4,
         '모두': 4,
         '비용': 4,
         '상': 4,
         '가르시아': 4,
         '코': 4,
         '트': 4,
         '임대': 4,
         '수상': 4,
         '개인': 4,
         '우승': 4,
         '포지션': 4,
         '파리': 4,
         '유벤투스': 4,
         '국가대표': 4,
         '스타일': 4,
         '더티': 4,
         '활용': 4,
         '압박': 4,
         '조르지뉴': 4,
         '가담': 4,
         '크게': 4,
         '함': 4,
         '결승': 4,
         '매너': 4,
         '코치': 4,
         '이번': 4,
         '어머니': 4,
         '아틀레': 4,
         '티코': 4,
         '마드리드': 4,
         '룰리': 4,
         '맥': 4,
         '알리스': 4,
         '곤살레스': 4,
         '의견': 4,
         '구도': 4,
         '뺨': 4,
         '제': 4,
         '사장': 4,
         '백혈병': 4,
         '관계': 4,
         '해': 4,
         '모정': 4,
         '이식': 4,
         '원장': 4,
         '신고': 4,
         '진실': 4,
         '곧': 4,
         '디자인': 4,
         '박사': 4,
         '은신': 4,
         '증거': 4,
         '기자회견': 4,
         '명령': 4,
         '기증': 4,
         '호의': 4,
         '오피스텔': 4,
         '자살': 4,
         '포기': 4,
         '고통': 4,
         '발연기': 4,
         '연기력': 4,
         '연출': 4,
         '출연': 4,
         '접기': 3,
         '철도': 3,
         '일반': 3,
         '향남': 3,
         '롯데': 3,
         '아트': 3,
         '홈플러스': 3,
         '스타': 3,
         '필드': 3,
         '형무소': 3,
         '감시탑': 3,
         '이야기': 3,
         '화면': 3,
         '총': 3,
         '치마': 3,
         '정상': 3,
         '드워프': 3,
         '통과': 3,
         '단': 3,
         '열': 3,
         '피격': 3,
         '치면': 3,
         '울': 3,
         '모드': 3,
         '본명': 3,
         '정말': 3,
         '입장': 3,
         '고라': 3,
         '그대로': 3,
         '보통': 3,
         '그때': 3,
         '요청': 3,
         '벌': 3,
         '성욕': 3,
         '약제사': 3,
         '제공': 3,
         '만능': 3,
         '달리': 3,
         '불명': 3,
         '해결': 3,
         '실제': 3,
         '모양': 3,
         '북동쪽': 3,
         '말로': 3,
         '놈': 3,
         '사정': 3,
         '구석': 3,
         '맵': 3,
         '감금': 3,
         '미노타우로스': 3,
         '수준': 3,
         '해도': 3,
         '꼭': 3,
         '최초': 3,
         '방법': 3,
         '열기': 3,
         '팔면': 3,
         '하라': 3,
         '남편': 3,
         '항의': 3,
         '부호': 3,
         '제일': 3,
         '마침': 3,
         '권유': 3,
         '해제': 3,
         '라면': 3,
         '관': 3,
         '소개': 3,
         '남쪽': 3,
         '근무': 3,
         '기도': 3,
         '메이드': 3,
         '게시': 3,
         '물': 3,
         '자고': 3,
         '노': 3,
         '베테': 3,
         '사나이': 3,
         '그냥': 3,
         '말리': 3,
         '뭐': 3,
         '상위': 3,
         '호환': 3,
         '교환': 3,
         '주지': 3,
         '줄거리': 3,
         '반전': 3,
         '요소': 3,
         '직': 3,
         '잠시': 3,
         '백합': 3,
         '성행위': 3,
         '부분': 3,
         '인': 3,
         '거지': 3,
         '카드': 3,
         '떡밥': 3,
         '체크메이트': 3,
         '규칙': 3,
         '직전': 3,
         '결정': 3,
         '턴': 3,
         '빈': 3,
         '제거': 3,
         '여부': 3,
         '수행': 3,
         '아이콘': 3,
         '무엇': 3,
         '코끼리': 3,
         '좌': 3,
         '원래': 3,
         '심': 3,
         '사자': 3,
         '준우승자': 3,
         '승은': 3,
         '스쿼드': 3,
         '소속': 3,
         '폴리': 3,
         '상트페테르부르크': 3,
         '생제르맹': 3,
         '보기': 3,
         '번호': 3,
         '대표팀': 3,
         '강점': 3,
         '슈팅': 3,
         '후방': 3,
         '중심': 3,
         '레': 3,
         '지스타': 3,
         '주력': 3,
         '비교': 3,
         '한번': 3,
         '하드': 3,
         '맨': 3,
         '역할': 3,
         '대부분': 3,
         '카타르': 3,
         '얼굴': 3,
         '리그': 3,
         '지난': 3,
         '나우': 3,
         '로드': 3,
         '이전': 3,
         '무려': 3,
         '차지': 3,
         '의료': 3,
         '듯이': 3,
         '무소': 3,
         '맨체스터': 3,
         '니콜라스': 3,
         '리버': 3,
         '아르마니': 3,
         '페첼': 3,
         '아쿠': 3,
         '마리아': 3,
         '코레아': 3,
         '로드리게스': 3,
         '스칼': 3,
         '수석': 3,
         '파블로': 3,
         '로베르토': 3,
         '아얄라왈테르': 3,
         '사무엘': 3,
         '학대': 3,
         '젖': 3,
         '얼마': 3,
         '결혼': 3,
         '악마': 3,
         '행적': 3,
         '진정': 3,
         '은': 3,
         '행방': 3,
         '유언': 3,
         '뺑소니': 3,
         '교통사고': 3,
         '실': 3,
         '주주': 3,
         '식구': 3,
         '방해': 3,
         '영': 3,
         '알리': 3,
         '증인': 3,
         '임': 3,
         '멘붕': 3,
         '해임': 3,
         '선포': 3,
         '결백': 3,
         '가짜': 3,
         '가게': 3,
         '무죄': 3,
         '당황': 3,
         '변명': 3,
         '세상': 3,
         '검사': 3,
         '과거': 3,
         '옆집': 3,
         '추궁': 3,
         '시청자': 3,
         '조사': 3,
         '면서': 3,
         '유출': 3,
         '화상': 3,
         '칫솔': 3,
         '마침내': 3,
         '타고': 3,
         '찰나': 3,
         '인생': 3,
         '짓': 3,
         '공장': 3,
         '모녀': 3,
         '혜주': 3,
         '널': 3,
         '바다': 3,
         '파도': 3,
         '친딸임': 3,
         '극': 3,
         '매몰': 3,
         '작': 3,
         '맥스': 3,
         '시설': 2,
         '공원': 2,
         '호수': 2,
         '담': 2,
         '시네마': 2,
         '호텔': 2,
         '이마트': 2,
         '동화': 2,
         '번역': 2,
         '한국': 2,
         '유튜브': 2,
         '주기': 2,
         '전신': 2,
         '건물': 2,
         '예': 2,
         '몇': 2,
         '빨간색': 2,
         '보라색': 2,
         '버그': 2,
         '생': 2,
         '겹': 2,
         '주인공': 2,
         '항상': 2,
         '눈동자': 2,
         '대략': 2,
         '초반': 2,
         '중반': 2,
         '예상': 2,
         '분투': 2,
         '반드시': 2,
         '처녀': 2,
         '거나': 2,
         '금발': 2,
         '형상': 2,
         '증상': 2,
         '완화': 2,
         '뿐': 2,
         '근본': 2,
         '성추행': 2,
         '고민': 2,
         '전달': 2,
         '평소': 2,
         '운영': 2,
         '그동안': 2,
         '때마침': 2,
         '흥분': 2,
         '고치': 2,
         '바니': 2,
         '지게': 2,
         '중년': 2,
         '주민': 2,
         '마냥': 2,
         '정작': 2,
         '자위': 2,
         '사냥': 2,
         '약재료': 2,
         '어째선': 2,
         '천지': 2,
         '팔': 2,
         '만': 2,
         '왈': 2,
         '치안': 2,
         '서쪽': 2,
         '목적': 2,
         '업자': 2,
         '남친': 2,
         '아마': 2,
         '범죄자': 2,
         '회상': 2,
         '슬': 2,
         '라임': 2,
         '사': 2,
         '방랑자': 2,
         '밖': 2,
         '생략': 2,
         '접수': 2,
         '취향': 2,
         '사병': 2,
         '료': 2,
         '집착': 2,
         '입': 2,
         '부자': 2,
         '제안': 2,
         '수단': 2,
         '겨우': 2,
         '성의': 2,
         '지급': 2,
         '만류': 2,
         '녀석': 2,
         '하룻밤': 2,
         '문지기': 2,
         '설국': 2,
         '경비원': 2,
         '낼': 2,
         '조심': 2,
         '명물': 2,
         '이면': 2,
         '말종': 2,
         '견습': 2,
         '수도사': 2,
         '방문': 2,
         '호탕': 2,
         '함부로': 2,
         '충고': 2,
         '성냥': 2,
         '관해': 2,
         '다가': 2,
         '안내': 2,
         '남동쪽': 2,
         '마치': 2,
         '귀부인': 2,
         '피해': 2,
         '시중': 2,
         '외모': 2,
         '범한': 2,
         '감고': 2,
         '애인': 2,
         '이국': 2,
         '이란': 2,
         '부부': 2,
         '음유시인': 2,
         '생활': 2,
         '대장장이': 2,
         '생전': 2,
         '요리': 2,
         '필사': 2,
         '아래': 2,
         '주자': 2,
         '쥐': 2,
         '피하': 2,
         '만남': 2,
         '대로': 2,
         '판매': 2,
         '봉인': 2,
         '낫': 2,
         '별': 2,
         '거치': 2,
         '사과': 2,
         '길목': 2,
         '나무': 2,
         '틀': 2,
         '루트': 2,
         '슬라임': 2,
         '직행': 2,
         '린다': 2,
         '배': 2,
         '래서': 2,
         '충족': 2,
         '밀': 2,
         '젠': 2,
         '절망': 2,
         '제목': 2,
         '영어': 2,
         '영문': 2,
         '배포': 2,
         ...})

In [38]:
#한글자 단어 제외시키기

# for x in count:
#     if len(x)>1:
#         {x: count[x]}

count2 = Counter({x:count[x] for x in count if len(x) > 1})
count2

Counter({'자신': 106,
         '해주': 105,
         '망토': 96,
         '마을': 96,
         '손여리': 79,
         '상태': 59,
         '편집': 58,
         '주호': 58,
         '도영': 55,
         '늑대': 50,
         '미스트': 49,
         '위해': 42,
         '매춘부': 39,
         '데스': 38,
         '사람': 36,
         '지원': 36,
         '마야': 36,
         '다시': 33,
         '파레': 33,
         '때문': 32,
         '계속': 30,
         '매춘': 30,
         '가야': 30,
         '게임': 29,
         '행동': 27,
         '도치': 27,
         '마녀': 26,
         '선수': 26,
         '의사': 25,
         '가지': 24,
         '하자': 24,
         '남자': 23,
         '이후': 23,
         '병사': 22,
         '아르헨티나': 22,
         '노스': 21,
         '아이템': 21,
         '엔딩': 21,
         '부탁': 21,
         '마르': 21,
         '월드컵': 21,
         '자식': 21,
         '동굴': 20,
         '마물': 20,
         '생각': 20,
         '아이': 20,
         '알몸': 19,
         '이동': 19,
         '인물': 19,
         '모든': 19,
         '수해': 18,
         '플레이': 18,
         '사냥꾼': 18,
         '폐허': 17,
         '대해': 17,
         '문서': 17,
         '수비': 17,
         '곧바로': 17,
         '사실': 16,
         '거절': 16,
         '네스': 16,
         '친딸': 16,
         '데리': 16,
         '찻집': 15,
         '다음': 15,
         '상대': 15,
         '망령': 15,
         '치료': 15,
         '하나': 15,
         '조건': 15,
         '대한': 15,
         '리가': 15,
         '해성': 15,
         '회장': 15,
         '말년': 15,
         '엄마': 14,
         '아들': 14,
         '마음': 14,
         '코인': 14,
         '라운드': 14,
         '김무열': 14,
         '전라': 13,
         '선택': 13,
         '모습': 13,
         '진행': 13,
         '자기': 13,
         '역시': 13,
         '라며': 13,
         '여자': 13,
         '바로': 13,
         '징표': 13,
         '경기': 13,
         '골수': 13,
         '전화': 13,
         '동탄': 12,
         '카지노': 12,
         '대사': 12,
         '경우': 12,
         '정도': 12,
         '요구': 12,
         '재료': 12,
         '성불': 12,
         '골드': 12,
         '오히려': 12,
         '요정': 12,
         '노인': 12,
         '손님': 12,
         '본인': 12,
         '패스': 12,
         '상황': 12,
         '악행': 12,
         '모성애': 12,
         '시작': 11,
         '남성': 11,
         '순간': 11,
         '소리': 11,
         '가슴': 11,
         '정보': 11,
         '보아': 11,
         '매우': 11,
         '이유': 11,
         '생물': 11,
         '간수': 11,
         '출현': 11,
         '승리': 11,
         '축구': 11,
         '메시': 11,
         '입양': 11,
         '얘기': 11,
         '지원이': 11,
         '할머니': 10,
         '몬스터': 10,
         '플레이어': 10,
         '시간': 10,
         '성격': 10,
         '이벤트': 10,
         '살찐': 10,
         '보고': 10,
         '등장': 10,
         '관리': 10,
         '마지막': 10,
         '포함': 10,
         '다람쥐': 10,
         '보카': 10,
         '주니어스': 10,
         '국가대표팀': 10,
         '당신': 10,
         '드라마': 10,
         '경찰': 10,
         '위드': 10,
         '무열': 10,
         '자수': 10,
         '수도': 9,
         '교회': 9,
         '강간': 9,
         '장면': 9,
         '가장': 9,
         '병원': 9,
         '청년': 9,
         '경고': 9,
         '여성': 9,
         '부랑': 9,
         '이상': 9,
         '이름': 9,
         '사망': 9,
         '이제': 9,
         '전부': 9,
         '문제': 9,
         '차례': 9,
         '특수': 9,
         '기물': 9,
         '사건': 9,
         '단점': 9,
         '퇴장': 9,
         '갑자기': 9,
         '주가': 9,
         '그룹': 9,
         '기억': 9,
         '개요': 8,
         '북서쪽': 8,
         '유적': 8,
         '반짇고리': 8,
         '스테이지': 8,
         '소녀': 8,
         '다만': 8,
         '신부': 8,
         '나중': 8,
         '할아버지': 8,
         '착용': 8,
         '위험': 8,
         '처음': 8,
         '어디': 8,
         '내용': 8,
         '소유': 8,
         '배치': 8,
         '종료': 8,
         '참고': 8,
         '대회': 8,
         '결승전': 8,
         '공격': 8,
         '파울': 8,
         '몰리나': 8,
         '주장': 8,
         '구해': 8,
         '보육원': 8,
         '협박': 8,
         '진짜': 8,
         '연락': 8,
         '아버지': 8,
         '화성': 7,
         '이스트': 7,
         '우드': 7,
         '매춘소': 7,
         '던전': 7,
         '인간': 7,
         '동충하초': 7,
         '정액': 7,
         '클리어': 7,
         '습격': 7,
         '버섯': 7,
         '질내사정': 7,
         '사랑': 7,
         '또한': 7,
         '도덕': 7,
         '통해': 7,
         '아저씨': 7,
         '퀘스트': 7,
         '정체': 7,
         '북쪽': 7,
         '범인': 7,
         '고블린': 7,
         '잘못': 7,
         '아가씨': 7,
         '차고': 7,
         '다른': 7,
         '부정': 7,
         '우리': 7,
         '확인': 7,
         '기분': 7,
         '심지어': 7,
         '사고': 7,
         '최종': 7,
         '충격': 7,
         '평가': 7,
         '방향': 7,
         '레안드로': 7,
         '코파': 7,
         '미드필더': 7,
         '논란': 7,
         '자체': 7,
         '감정': 7,
         '아기': 7,
         '치가': 7,
         '이혼': 7,
         '경찰서': 7,
         '회사': 7,
         '라이터': 7,
         '스토리': 6,
         '진료': 6,
         '성당': 6,
         '배드': 6,
         '치기': 6,
         '예인': 6,
         '스스로': 6,
         '입구': 6,
         '시엔': 6,
         '동안': 6,
         '돼지': 6,
         '이용': 6,
         '시도': 6,
         '목격': 6,
         '언니': 6,
         '가족': 6,
         '달라': 6,
         '동쪽': 6,
         '촌장': 6,
         '행위': 6,
         '산적': 6,
         '걱정': 6,
         '전혀': 6,
         '자리': 6,
         '간다': 6,
         '지금': 6,
         '자주': 6,
         '강제': 6,
         '미리': 6,
         '여기': 6,
         '직접': 6,
         '상처': 6,
         '탈리아': 6,
         '라시': 6,
         '오스': 6,
         '로메': 6,
         '감독': 6,
         '아메리카': 6,
         '경력': 6,
         '폭행': 6,
         '태클': 6,
         '싸움': 6,
         '네덜란드': 6,
         '스페인': 6,
         '선언': 6,
         '리오넬': 6,
         '멘디': 6,
         '배우': 6,
         '배종옥': 6,
         '소식': 6,
         '친모': 6,
         '교도소': 6,
         '눈치': 6,
         '비서': 6,
         '고속': 5,
         '고속도로': 5,
         '클럽': 5,
         '사막': 5,
         '소문': 5,
         '오버': 5,
         '사용': 5,
         '동생': 5,
         '성수': 5,
         '로자리오': 5,
         '언급': 5,
         '성폭행': 5,
         '사이': 5,
         '제외': 5,
         '부적': 5,
         '가면': 5,
         '대신': 5,
         '주의': 5,
         '현재': 5,
         '보이': 5,
         '남자에게': 5,
         '설명': 5,
         '거대': 5,
         '수녀': 5,
         '손녀': 5,
         '조금': 5,
         '동의': 5,
         '아내': 5,
         '누가': 5,
         '여행자': 5,
         '수가': 5,
         '손자': 5,
         '결말': 5,
         '반응': 5,
         '서로': 5,
         '소원': 5,
         '관련': 5,
         '여담': 5,
         '횟수': 5,
         '가격': 5,
         '해당': 5,
         '표기': 5,
         '능력': 5,
         '로마': 5,
         '제니트': 5,
         '기록': 5,
         '악역': 5,
         '죽지': 5,
         '분노': 5,
         '벤치': 5,
         '비판': 5,
         '제대로': 5,
         '피코': 5,
         '몬티': 5,
         '페르': 5,
         '알바': 5,
         '레스': 5,
         '명단': 5,
         '조작': 5,
         '납치': 5,
         '에손': 5,
         '의심': 5,
         '계략': 5,
         '계획': 5,
         '연기': 5,
         '거짓말': 5,
         '비밀': 5,
         '도중': 5,
         '설득': 5,
         '용서': 5,
         '통행': 4,
         '상인': 4,
         '영상': 4,
         '예전': 4,
         '여동생': 4,
         '감염': 4,
         '단계': 4,
         '피임': 4,
         '질문': 4,
         '대쉬': 4,
         '일부': 4,
         '오브': 4,
         '촉수': 4,
         '성관계': 4,
         '나이': 4,
         '추정': 4,
         '부잣집': 4,
         '인지': 4,
         '편이': 4,
         '성적': 4,
         '도움': 4,
         '집안': 4,
         '더욱': 4,
         '변태': 4,
         '고양이': 4,
         '길이': 4,
         '태도': 4,
         '관광객': 4,
         '관광': 4,
         '지적': 4,
         '소년': 4,
         '실상': 4,
         '누구': 4,
         '중인': 4,
         '구매': 4,
         '위치': 4,
         '커피': 4,
         '만약': 4,
         '몰래': 4,
         '상담': 4,
         '안정': 4,
         '눈물': 4,
         '점주': 4,
         '부인': 4,
         '승낙': 4,
         '진입': 4,
         '애플파이': 4,
         '에릭': 4,
         '아무': 4,
         '스포일러': 4,
         '작품': 4,
         '간접': 4,
         '키스': 4,
         '세계': 4,
         '도망': 4,
         '그것': 4,
         '다그': 4,
         '가운데': 4,
         '결과': 4,
         '환불': 4,
         '모두': 4,
         '비용': 4,
         '가르시아': 4,
         '임대': 4,
         '수상': 4,
         '개인': 4,
         '우승': 4,
         '포지션': 4,
         '파리': 4,
         '유벤투스': 4,
         '국가대표': 4,
         '스타일': 4,
         '더티': 4,
         '활용': 4,
         '압박': 4,
         '조르지뉴': 4,
         '가담': 4,
         '크게': 4,
         '결승': 4,
         '매너': 4,
         '코치': 4,
         '이번': 4,
         '어머니': 4,
         '아틀레': 4,
         '티코': 4,
         '마드리드': 4,
         '룰리': 4,
         '알리스': 4,
         '곤살레스': 4,
         '의견': 4,
         '구도': 4,
         '사장': 4,
         '백혈병': 4,
         '관계': 4,
         '모정': 4,
         '이식': 4,
         '원장': 4,
         '신고': 4,
         '진실': 4,
         '디자인': 4,
         '박사': 4,
         '은신': 4,
         '증거': 4,
         '기자회견': 4,
         '명령': 4,
         '기증': 4,
         '호의': 4,
         '오피스텔': 4,
         '자살': 4,
         '포기': 4,
         '고통': 4,
         '발연기': 4,
         '연기력': 4,
         '연출': 4,
         '출연': 4,
         '접기': 3,
         '철도': 3,
         '일반': 3,
         '향남': 3,
         '롯데': 3,
         '아트': 3,
         '홈플러스': 3,
         '스타': 3,
         '필드': 3,
         '형무소': 3,
         '감시탑': 3,
         '이야기': 3,
         '화면': 3,
         '치마': 3,
         '정상': 3,
         '드워프': 3,
         '통과': 3,
         '피격': 3,
         '치면': 3,
         '모드': 3,
         '본명': 3,
         '정말': 3,
         '입장': 3,
         '고라': 3,
         '그대로': 3,
         '보통': 3,
         '그때': 3,
         '요청': 3,
         '성욕': 3,
         '약제사': 3,
         '제공': 3,
         '만능': 3,
         '달리': 3,
         '불명': 3,
         '해결': 3,
         '실제': 3,
         '모양': 3,
         '북동쪽': 3,
         '말로': 3,
         '사정': 3,
         '구석': 3,
         '감금': 3,
         '미노타우로스': 3,
         '수준': 3,
         '해도': 3,
         '최초': 3,
         '방법': 3,
         '열기': 3,
         '팔면': 3,
         '하라': 3,
         '남편': 3,
         '항의': 3,
         '부호': 3,
         '제일': 3,
         '마침': 3,
         '권유': 3,
         '해제': 3,
         '라면': 3,
         '소개': 3,
         '남쪽': 3,
         '근무': 3,
         '기도': 3,
         '메이드': 3,
         '게시': 3,
         '자고': 3,
         '베테': 3,
         '사나이': 3,
         '그냥': 3,
         '말리': 3,
         '상위': 3,
         '호환': 3,
         '교환': 3,
         '주지': 3,
         '줄거리': 3,
         '반전': 3,
         '요소': 3,
         '잠시': 3,
         '백합': 3,
         '성행위': 3,
         '부분': 3,
         '거지': 3,
         '카드': 3,
         '떡밥': 3,
         '체크메이트': 3,
         '규칙': 3,
         '직전': 3,
         '결정': 3,
         '제거': 3,
         '여부': 3,
         '수행': 3,
         '아이콘': 3,
         '무엇': 3,
         '코끼리': 3,
         '원래': 3,
         '사자': 3,
         '준우승자': 3,
         '승은': 3,
         '스쿼드': 3,
         '소속': 3,
         '폴리': 3,
         '상트페테르부르크': 3,
         '생제르맹': 3,
         '보기': 3,
         '번호': 3,
         '대표팀': 3,
         '강점': 3,
         '슈팅': 3,
         '후방': 3,
         '중심': 3,
         '지스타': 3,
         '주력': 3,
         '비교': 3,
         '한번': 3,
         '하드': 3,
         '역할': 3,
         '대부분': 3,
         '카타르': 3,
         '얼굴': 3,
         '리그': 3,
         '지난': 3,
         '나우': 3,
         '로드': 3,
         '이전': 3,
         '무려': 3,
         '차지': 3,
         '의료': 3,
         '듯이': 3,
         '무소': 3,
         '맨체스터': 3,
         '니콜라스': 3,
         '리버': 3,
         '아르마니': 3,
         '페첼': 3,
         '아쿠': 3,
         '마리아': 3,
         '코레아': 3,
         '로드리게스': 3,
         '스칼': 3,
         '수석': 3,
         '파블로': 3,
         '로베르토': 3,
         '아얄라왈테르': 3,
         '사무엘': 3,
         '학대': 3,
         '얼마': 3,
         '결혼': 3,
         '악마': 3,
         '행적': 3,
         '진정': 3,
         '행방': 3,
         '유언': 3,
         '뺑소니': 3,
         '교통사고': 3,
         '주주': 3,
         '식구': 3,
         '방해': 3,
         '알리': 3,
         '증인': 3,
         '멘붕': 3,
         '해임': 3,
         '선포': 3,
         '결백': 3,
         '가짜': 3,
         '가게': 3,
         '무죄': 3,
         '당황': 3,
         '변명': 3,
         '세상': 3,
         '검사': 3,
         '과거': 3,
         '옆집': 3,
         '추궁': 3,
         '시청자': 3,
         '조사': 3,
         '면서': 3,
         '유출': 3,
         '화상': 3,
         '칫솔': 3,
         '마침내': 3,
         '타고': 3,
         '찰나': 3,
         '인생': 3,
         '공장': 3,
         '모녀': 3,
         '혜주': 3,
         '바다': 3,
         '파도': 3,
         '친딸임': 3,
         '매몰': 3,
         '맥스': 3,
         '시설': 2,
         '공원': 2,
         '호수': 2,
         '시네마': 2,
         '호텔': 2,
         '이마트': 2,
         '동화': 2,
         '번역': 2,
         '한국': 2,
         '유튜브': 2,
         '주기': 2,
         '전신': 2,
         '건물': 2,
         '빨간색': 2,
         '보라색': 2,
         '버그': 2,
         '주인공': 2,
         '항상': 2,
         '눈동자': 2,
         '대략': 2,
         '초반': 2,
         '중반': 2,
         '예상': 2,
         '분투': 2,
         '반드시': 2,
         '처녀': 2,
         '거나': 2,
         '금발': 2,
         '형상': 2,
         '증상': 2,
         '완화': 2,
         '근본': 2,
         '성추행': 2,
         '고민': 2,
         '전달': 2,
         '평소': 2,
         '운영': 2,
         '그동안': 2,
         '때마침': 2,
         '흥분': 2,
         '고치': 2,
         '바니': 2,
         '지게': 2,
         '중년': 2,
         '주민': 2,
         '마냥': 2,
         '정작': 2,
         '자위': 2,
         '사냥': 2,
         '약재료': 2,
         '어째선': 2,
         '천지': 2,
         '치안': 2,
         '서쪽': 2,
         '목적': 2,
         '업자': 2,
         '남친': 2,
         '아마': 2,
         '범죄자': 2,
         '회상': 2,
         '라임': 2,
         '방랑자': 2,
         '생략': 2,
         '접수': 2,
         '취향': 2,
         '사병': 2,
         '집착': 2,
         '부자': 2,
         '제안': 2,
         '수단': 2,
         '겨우': 2,
         '성의': 2,
         '지급': 2,
         '만류': 2,
         '녀석': 2,
         '하룻밤': 2,
         '문지기': 2,
         '설국': 2,
         '경비원': 2,
         '조심': 2,
         '명물': 2,
         '이면': 2,
         '말종': 2,
         '견습': 2,
         '수도사': 2,
         '방문': 2,
         '호탕': 2,
         '함부로': 2,
         '충고': 2,
         '성냥': 2,
         '관해': 2,
         '다가': 2,
         '안내': 2,
         '남동쪽': 2,
         '마치': 2,
         '귀부인': 2,
         '피해': 2,
         '시중': 2,
         '외모': 2,
         '범한': 2,
         '감고': 2,
         '애인': 2,
         '이국': 2,
         '이란': 2,
         '부부': 2,
         '음유시인': 2,
         '생활': 2,
         '대장장이': 2,
         '생전': 2,
         '요리': 2,
         '필사': 2,
         '아래': 2,
         '주자': 2,
         '피하': 2,
         '만남': 2,
         '대로': 2,
         '판매': 2,
         '봉인': 2,
         '거치': 2,
         '사과': 2,
         '길목': 2,
         '나무': 2,
         '루트': 2,
         '슬라임': 2,
         '직행': 2,
         '린다': 2,
         '래서': 2,
         '충족': 2,
         '절망': 2,
         '제목': 2,
         '영어': 2,
         '영문': 2,
         '배포': 2,
         '주로': 2,
         '실수': 2,
         '거의': 2,
         '처리': 2,
         '중이': 2,
         '여러': 2,
         '모서리': 2,
         '프로': 2,
         '참가자': 2,
         '에피소드': 2,
         '공개': 2,
         '정리': 2,
         '먼저': 2,
         '패자': 2,
         '제한': 2,
         '다행': 2,
         '종류': 2,
         '존재': 2,
         '소모': 2,
         '소유권': 2,
         '변경': 2,
         '상대방': 2,
         '상점': 2,
         '점등': 2,
         '바탕': 2,
         '추리': 2,
         '구성': 2,
         '두더지': 2,
         '기회': 2,
         '추가': 2,
         '기념품': 2,
         '운명': 2,
         '보유': 2,
         '성공': 2,
         '불사': 2,
         '재경기': 2,
         '체신': 2,
         '멤버': 2,
         '출생': 2,
         '국적': 2,
         '신체': 2,
         '오른발': 2,
         '보베': 2,
         '로나': 2,
         '편집자': 2,
         '세한': 2,
         '활약': 2,
         '최대': 2,
         '만큼': 2,
         '아웃': 2,
         '구사': 2,
         '유형': 2,
         '플레이메이커': 2,
         '취약': 2,
         '활동량': 2,
         '범위': 2,
         '전방': 2,
         '롱킥': 2,
         '습관': 2,
         '내지': 2,
         '무대': 2,
         '스킬': 2,
         '경전': 2,
         '옐로카드': 2,
         '분명': 2,
         '정신': 2,
         '감치': 2,
         '유독': 2,
         '쿠프': 2,
         '반칙': 2,
         '직후': 2,
         '의문': 2,
         '제기': 2,
         '패배': 2,
         '복부': 2,
         '간의': 2,
         '전체': 2,
         '저번': 2,
         '누적': 2,
         '이미지': 2,
         '역사상': 2,
         '최악': 2,
         '출장': 2,
         '징계': 2,
         '출전': 2,
         '자격': 2,
         '에밀': 2,
         '리아노': 2,
         '대장': 2,
         '전쟁': 2,
         '출신': 2,
         '축구선수': 2,
         '활동': 2,
         '시티': 2,
         '첼시': 2,
         '네시': 2,
         '메디나': 2,
         '니코': 2,
         '파스': 2,
         '로페스': 2,
         '콰르타': 2,
         '고메스': 2,
         '스칼로': 2,
         '기준': 2,
         '커버': 2,
         '막바지': 2,
         '급속도': 2,
         '골프': 2,
         '보디빌더': 2,
         '외손': 2,
         '심부름': 2,
         '진단': 2,
         '일치': 2,
         '명대사': 2,
         '중간': 2,
         '이의': 2,
         '거부': 2,
         '재회': 2,
         '딸봄': 2,
         '윤설': 2,
         '부하': 2,
         '책상': 2,
         '양부모': 2,
         '탈옥': 2,
         '고발': 2,
         '거짓': 2,
         '준비': 2,
         '무너': 2,
         '리기': 2,
         '동영상': 2,
         '서구': 2,
         '장애': 2,
         '증거불충분': 2,
         '경영': 2,
         '참여': 2,
         '체포': 2,
         '윤기': 2,
         '들통': 2,
         '취소': 2,
         '매출': 2,
         '후견인': 2,
         '위기': 2,
         '취하': 2,
         '어차피': 2,
         '횡령': 2,
         '노리': 2,
         '초대': 2,
         '주식': 2,
         '퇴원': 2,
         '녹음': 2,
         '서재': 2,
         '오라': 2,
         '시장': 2,
         '며칠': 2,
         '울분': 2,
         '증언': 2,
         '생사': 2,
         '두절': 2,
         '박람회': 2,
         '비난': 2,
         '끝내': 2,
         '자백': 2,
         '거리': 2,
         '무슨': 2,
         '이제야': 2,
         '주머니': 2,
         '기적': 2,
         '보호자': 2,
         '우연': 2,
         '막장': 2,
         '계단': 2,
         '불안감': 2,
         '오지': 2,
         '박대': 2,
         '최미희': 2,
         '신의': 2,
         '무언가': 2,
         '숨기': 2,
         '어깨': 2,
         '이기': 2,
         '도영은': 2,
         ...})

In [ ]:
# df2 = (
#     pd.DataFrame(count2.items(), columns=['word', 'count'])
#     .sort_values('count', ascending=False)
#     .reset_index(drop=True)
# )
# df2

      word  count
0       자신    106
1       해주    105
2       망토     96
3       마을     96
4      손여리     79
...    ...    ...
2233    고려      1
2234    위증      1
2235    고의      1
2236  시아버지      1
2237    유통      1

[2238 rows x 2 columns]

In [42]:
stopwords = ['상위', '문서', '내용', '누설', '아래', '해당', '설명', '표기', '추가', '모든', '사용', '매우', '가장',
            '줄거리', '요소', '상황', '편집', '틀', '경우', '때문', '모습', '정도', '이후', '사실', '생각', '인물',
            '이름', '년월']

count3 = Counter({x:count2[x] for x in count2 if x not in stopwords})
count3

Counter({'자신': 106,
         '해주': 105,
         '망토': 96,
         '마을': 96,
         '손여리': 79,
         '상태': 59,
         '주호': 58,
         '도영': 55,
         '늑대': 50,
         '미스트': 49,
         '위해': 42,
         '매춘부': 39,
         '데스': 38,
         '사람': 36,
         '지원': 36,
         '마야': 36,
         '다시': 33,
         '파레': 33,
         '계속': 30,
         '매춘': 30,
         '가야': 30,
         '게임': 29,
         '행동': 27,
         '도치': 27,
         '마녀': 26,
         '선수': 26,
         '의사': 25,
         '가지': 24,
         '하자': 24,
         '남자': 23,
         '병사': 22,
         '아르헨티나': 22,
         '노스': 21,
         '아이템': 21,
         '엔딩': 21,
         '부탁': 21,
         '마르': 21,
         '월드컵': 21,
         '자식': 21,
         '동굴': 20,
         '마물': 20,
         '아이': 20,
         '알몸': 19,
         '이동': 19,
         '수해': 18,
         '플레이': 18,
         '사냥꾼': 18,
         '폐허': 17,
         '대해': 17,
         '수비': 17,
         '곧바로': 17,
         '거절': 16,
         '네스': 16,
         '친딸': 16,
         '데리': 16,
         '찻집': 15,
         '다음': 15,
         '상대': 15,
         '망령': 15,
         '치료': 15,
         '하나': 15,
         '조건': 15,
         '대한': 15,
         '리가': 15,
         '해성': 15,
         '회장': 15,
         '말년': 15,
         '엄마': 14,
         '아들': 14,
         '마음': 14,
         '코인': 14,
         '라운드': 14,
         '김무열': 14,
         '전라': 13,
         '선택': 13,
         '진행': 13,
         '자기': 13,
         '역시': 13,
         '라며': 13,
         '여자': 13,
         '바로': 13,
         '징표': 13,
         '경기': 13,
         '골수': 13,
         '전화': 13,
         '동탄': 12,
         '카지노': 12,
         '대사': 12,
         '요구': 12,
         '재료': 12,
         '성불': 12,
         '골드': 12,
         '오히려': 12,
         '요정': 12,
         '노인': 12,
         '손님': 12,
         '본인': 12,
         '패스': 12,
         '악행': 12,
         '모성애': 12,
         '시작': 11,
         '남성': 11,
         '순간': 11,
         '소리': 11,
         '가슴': 11,
         '정보': 11,
         '보아': 11,
         '이유': 11,
         '생물': 11,
         '간수': 11,
         '출현': 11,
         '승리': 11,
         '축구': 11,
         '메시': 11,
         '입양': 11,
         '얘기': 11,
         '지원이': 11,
         '할머니': 10,
         '몬스터': 10,
         '플레이어': 10,
         '시간': 10,
         '성격': 10,
         '이벤트': 10,
         '살찐': 10,
         '보고': 10,
         '등장': 10,
         '관리': 10,
         '마지막': 10,
         '포함': 10,
         '다람쥐': 10,
         '보카': 10,
         '주니어스': 10,
         '국가대표팀': 10,
         '당신': 10,
         '드라마': 10,
         '경찰': 10,
         '위드': 10,
         '무열': 10,
         '자수': 10,
         '수도': 9,
         '교회': 9,
         '강간': 9,
         '장면': 9,
         '병원': 9,
         '청년': 9,
         '경고': 9,
         '여성': 9,
         '부랑': 9,
         '이상': 9,
         '사망': 9,
         '이제': 9,
         '전부': 9,
         '문제': 9,
         '차례': 9,
         '특수': 9,
         '기물': 9,
         '사건': 9,
         '단점': 9,
         '퇴장': 9,
         '갑자기': 9,
         '주가': 9,
         '그룹': 9,
         '기억': 9,
         '개요': 8,
         '북서쪽': 8,
         '유적': 8,
         '반짇고리': 8,
         '스테이지': 8,
         '소녀': 8,
         '다만': 8,
         '신부': 8,
         '나중': 8,
         '할아버지': 8,
         '착용': 8,
         '위험': 8,
         '처음': 8,
         '어디': 8,
         '소유': 8,
         '배치': 8,
         '종료': 8,
         '참고': 8,
         '대회': 8,
         '결승전': 8,
         '공격': 8,
         '파울': 8,
         '몰리나': 8,
         '주장': 8,
         '구해': 8,
         '보육원': 8,
         '협박': 8,
         '진짜': 8,
         '연락': 8,
         '아버지': 8,
         '화성': 7,
         '이스트': 7,
         '우드': 7,
         '매춘소': 7,
         '던전': 7,
         '인간': 7,
         '동충하초': 7,
         '정액': 7,
         '클리어': 7,
         '습격': 7,
         '버섯': 7,
         '질내사정': 7,
         '사랑': 7,
         '또한': 7,
         '도덕': 7,
         '통해': 7,
         '아저씨': 7,
         '퀘스트': 7,
         '정체': 7,
         '북쪽': 7,
         '범인': 7,
         '고블린': 7,
         '잘못': 7,
         '아가씨': 7,
         '차고': 7,
         '다른': 7,
         '부정': 7,
         '우리': 7,
         '확인': 7,
         '기분': 7,
         '심지어': 7,
         '사고': 7,
         '최종': 7,
         '충격': 7,
         '평가': 7,
         '방향': 7,
         '레안드로': 7,
         '코파': 7,
         '미드필더': 7,
         '논란': 7,
         '자체': 7,
         '감정': 7,
         '아기': 7,
         '치가': 7,
         '이혼': 7,
         '경찰서': 7,
         '회사': 7,
         '라이터': 7,
         '스토리': 6,
         '진료': 6,
         '성당': 6,
         '배드': 6,
         '치기': 6,
         '예인': 6,
         '스스로': 6,
         '입구': 6,
         '시엔': 6,
         '동안': 6,
         '돼지': 6,
         '이용': 6,
         '시도': 6,
         '목격': 6,
         '언니': 6,
         '가족': 6,
         '달라': 6,
         '동쪽': 6,
         '촌장': 6,
         '행위': 6,
         '산적': 6,
         '걱정': 6,
         '전혀': 6,
         '자리': 6,
         '간다': 6,
         '지금': 6,
         '자주': 6,
         '강제': 6,
         '미리': 6,
         '여기': 6,
         '직접': 6,
         '상처': 6,
         '탈리아': 6,
         '라시': 6,
         '오스': 6,
         '로메': 6,
         '감독': 6,
         '아메리카': 6,
         '경력': 6,
         '폭행': 6,
         '태클': 6,
         '싸움': 6,
         '네덜란드': 6,
         '스페인': 6,
         '선언': 6,
         '리오넬': 6,
         '멘디': 6,
         '배우': 6,
         '배종옥': 6,
         '소식': 6,
         '친모': 6,
         '교도소': 6,
         '눈치': 6,
         '비서': 6,
         '고속': 5,
         '고속도로': 5,
         '클럽': 5,
         '사막': 5,
         '소문': 5,
         '오버': 5,
         '동생': 5,
         '성수': 5,
         '로자리오': 5,
         '언급': 5,
         '성폭행': 5,
         '사이': 5,
         '제외': 5,
         '부적': 5,
         '가면': 5,
         '대신': 5,
         '주의': 5,
         '현재': 5,
         '보이': 5,
         '남자에게': 5,
         '거대': 5,
         '수녀': 5,
         '손녀': 5,
         '조금': 5,
         '동의': 5,
         '아내': 5,
         '누가': 5,
         '여행자': 5,
         '수가': 5,
         '손자': 5,
         '결말': 5,
         '반응': 5,
         '서로': 5,
         '소원': 5,
         '관련': 5,
         '여담': 5,
         '횟수': 5,
         '가격': 5,
         '능력': 5,
         '로마': 5,
         '제니트': 5,
         '기록': 5,
         '악역': 5,
         '죽지': 5,
         '분노': 5,
         '벤치': 5,
         '비판': 5,
         '제대로': 5,
         '피코': 5,
         '몬티': 5,
         '페르': 5,
         '알바': 5,
         '레스': 5,
         '명단': 5,
         '조작': 5,
         '납치': 5,
         '에손': 5,
         '의심': 5,
         '계략': 5,
         '계획': 5,
         '연기': 5,
         '거짓말': 5,
         '비밀': 5,
         '도중': 5,
         '설득': 5,
         '용서': 5,
         '통행': 4,
         '상인': 4,
         '영상': 4,
         '예전': 4,
         '여동생': 4,
         '감염': 4,
         '단계': 4,
         '피임': 4,
         '질문': 4,
         '대쉬': 4,
         '일부': 4,
         '오브': 4,
         '촉수': 4,
         '성관계': 4,
         '나이': 4,
         '추정': 4,
         '부잣집': 4,
         '인지': 4,
         '편이': 4,
         '성적': 4,
         '도움': 4,
         '집안': 4,
         '더욱': 4,
         '변태': 4,
         '고양이': 4,
         '길이': 4,
         '태도': 4,
         '관광객': 4,
         '관광': 4,
         '지적': 4,
         '소년': 4,
         '실상': 4,
         '누구': 4,
         '중인': 4,
         '구매': 4,
         '위치': 4,
         '커피': 4,
         '만약': 4,
         '몰래': 4,
         '상담': 4,
         '안정': 4,
         '눈물': 4,
         '점주': 4,
         '부인': 4,
         '승낙': 4,
         '진입': 4,
         '애플파이': 4,
         '에릭': 4,
         '아무': 4,
         '스포일러': 4,
         '작품': 4,
         '간접': 4,
         '키스': 4,
         '세계': 4,
         '도망': 4,
         '그것': 4,
         '다그': 4,
         '가운데': 4,
         '결과': 4,
         '환불': 4,
         '모두': 4,
         '비용': 4,
         '가르시아': 4,
         '임대': 4,
         '수상': 4,
         '개인': 4,
         '우승': 4,
         '포지션': 4,
         '파리': 4,
         '유벤투스': 4,
         '국가대표': 4,
         '스타일': 4,
         '더티': 4,
         '활용': 4,
         '압박': 4,
         '조르지뉴': 4,
         '가담': 4,
         '크게': 4,
         '결승': 4,
         '매너': 4,
         '코치': 4,
         '이번': 4,
         '어머니': 4,
         '아틀레': 4,
         '티코': 4,
         '마드리드': 4,
         '룰리': 4,
         '알리스': 4,
         '곤살레스': 4,
         '의견': 4,
         '구도': 4,
         '사장': 4,
         '백혈병': 4,
         '관계': 4,
         '모정': 4,
         '이식': 4,
         '원장': 4,
         '신고': 4,
         '진실': 4,
         '디자인': 4,
         '박사': 4,
         '은신': 4,
         '증거': 4,
         '기자회견': 4,
         '명령': 4,
         '기증': 4,
         '호의': 4,
         '오피스텔': 4,
         '자살': 4,
         '포기': 4,
         '고통': 4,
         '발연기': 4,
         '연기력': 4,
         '연출': 4,
         '출연': 4,
         '접기': 3,
         '철도': 3,
         '일반': 3,
         '향남': 3,
         '롯데': 3,
         '아트': 3,
         '홈플러스': 3,
         '스타': 3,
         '필드': 3,
         '형무소': 3,
         '감시탑': 3,
         '이야기': 3,
         '화면': 3,
         '치마': 3,
         '정상': 3,
         '드워프': 3,
         '통과': 3,
         '피격': 3,
         '치면': 3,
         '모드': 3,
         '본명': 3,
         '정말': 3,
         '입장': 3,
         '고라': 3,
         '그대로': 3,
         '보통': 3,
         '그때': 3,
         '요청': 3,
         '성욕': 3,
         '약제사': 3,
         '제공': 3,
         '만능': 3,
         '달리': 3,
         '불명': 3,
         '해결': 3,
         '실제': 3,
         '모양': 3,
         '북동쪽': 3,
         '말로': 3,
         '사정': 3,
         '구석': 3,
         '감금': 3,
         '미노타우로스': 3,
         '수준': 3,
         '해도': 3,
         '최초': 3,
         '방법': 3,
         '열기': 3,
         '팔면': 3,
         '하라': 3,
         '남편': 3,
         '항의': 3,
         '부호': 3,
         '제일': 3,
         '마침': 3,
         '권유': 3,
         '해제': 3,
         '라면': 3,
         '소개': 3,
         '남쪽': 3,
         '근무': 3,
         '기도': 3,
         '메이드': 3,
         '게시': 3,
         '자고': 3,
         '베테': 3,
         '사나이': 3,
         '그냥': 3,
         '말리': 3,
         '호환': 3,
         '교환': 3,
         '주지': 3,
         '반전': 3,
         '잠시': 3,
         '백합': 3,
         '성행위': 3,
         '부분': 3,
         '거지': 3,
         '카드': 3,
         '떡밥': 3,
         '체크메이트': 3,
         '규칙': 3,
         '직전': 3,
         '결정': 3,
         '제거': 3,
         '여부': 3,
         '수행': 3,
         '아이콘': 3,
         '무엇': 3,
         '코끼리': 3,
         '원래': 3,
         '사자': 3,
         '준우승자': 3,
         '승은': 3,
         '스쿼드': 3,
         '소속': 3,
         '폴리': 3,
         '상트페테르부르크': 3,
         '생제르맹': 3,
         '보기': 3,
         '번호': 3,
         '대표팀': 3,
         '강점': 3,
         '슈팅': 3,
         '후방': 3,
         '중심': 3,
         '지스타': 3,
         '주력': 3,
         '비교': 3,
         '한번': 3,
         '하드': 3,
         '역할': 3,
         '대부분': 3,
         '카타르': 3,
         '얼굴': 3,
         '리그': 3,
         '지난': 3,
         '나우': 3,
         '로드': 3,
         '이전': 3,
         '무려': 3,
         '차지': 3,
         '의료': 3,
         '듯이': 3,
         '무소': 3,
         '맨체스터': 3,
         '니콜라스': 3,
         '리버': 3,
         '아르마니': 3,
         '페첼': 3,
         '아쿠': 3,
         '마리아': 3,
         '코레아': 3,
         '로드리게스': 3,
         '스칼': 3,
         '수석': 3,
         '파블로': 3,
         '로베르토': 3,
         '아얄라왈테르': 3,
         '사무엘': 3,
         '학대': 3,
         '얼마': 3,
         '결혼': 3,
         '악마': 3,
         '행적': 3,
         '진정': 3,
         '행방': 3,
         '유언': 3,
         '뺑소니': 3,
         '교통사고': 3,
         '주주': 3,
         '식구': 3,
         '방해': 3,
         '알리': 3,
         '증인': 3,
         '멘붕': 3,
         '해임': 3,
         '선포': 3,
         '결백': 3,
         '가짜': 3,
         '가게': 3,
         '무죄': 3,
         '당황': 3,
         '변명': 3,
         '세상': 3,
         '검사': 3,
         '과거': 3,
         '옆집': 3,
         '추궁': 3,
         '시청자': 3,
         '조사': 3,
         '면서': 3,
         '유출': 3,
         '화상': 3,
         '칫솔': 3,
         '마침내': 3,
         '타고': 3,
         '찰나': 3,
         '인생': 3,
         '공장': 3,
         '모녀': 3,
         '혜주': 3,
         '바다': 3,
         '파도': 3,
         '친딸임': 3,
         '매몰': 3,
         '맥스': 3,
         '시설': 2,
         '공원': 2,
         '호수': 2,
         '시네마': 2,
         '호텔': 2,
         '이마트': 2,
         '동화': 2,
         '번역': 2,
         '한국': 2,
         '유튜브': 2,
         '주기': 2,
         '전신': 2,
         '건물': 2,
         '빨간색': 2,
         '보라색': 2,
         '버그': 2,
         '주인공': 2,
         '항상': 2,
         '눈동자': 2,
         '대략': 2,
         '초반': 2,
         '중반': 2,
         '예상': 2,
         '분투': 2,
         '반드시': 2,
         '처녀': 2,
         '거나': 2,
         '금발': 2,
         '형상': 2,
         '증상': 2,
         '완화': 2,
         '근본': 2,
         '성추행': 2,
         '고민': 2,
         '전달': 2,
         '평소': 2,
         '운영': 2,
         '그동안': 2,
         '때마침': 2,
         '흥분': 2,
         '고치': 2,
         '바니': 2,
         '지게': 2,
         '중년': 2,
         '주민': 2,
         '마냥': 2,
         '정작': 2,
         '자위': 2,
         '사냥': 2,
         '약재료': 2,
         '어째선': 2,
         '천지': 2,
         '치안': 2,
         '서쪽': 2,
         '목적': 2,
         '업자': 2,
         '남친': 2,
         '아마': 2,
         '범죄자': 2,
         '회상': 2,
         '라임': 2,
         '방랑자': 2,
         '생략': 2,
         '접수': 2,
         '취향': 2,
         '사병': 2,
         '집착': 2,
         '부자': 2,
         '제안': 2,
         '수단': 2,
         '겨우': 2,
         '성의': 2,
         '지급': 2,
         '만류': 2,
         '녀석': 2,
         '하룻밤': 2,
         '문지기': 2,
         '설국': 2,
         '경비원': 2,
         '조심': 2,
         '명물': 2,
         '이면': 2,
         '말종': 2,
         '견습': 2,
         '수도사': 2,
         '방문': 2,
         '호탕': 2,
         '함부로': 2,
         '충고': 2,
         '성냥': 2,
         '관해': 2,
         '다가': 2,
         '안내': 2,
         '남동쪽': 2,
         '마치': 2,
         '귀부인': 2,
         '피해': 2,
         '시중': 2,
         '외모': 2,
         '범한': 2,
         '감고': 2,
         '애인': 2,
         '이국': 2,
         '이란': 2,
         '부부': 2,
         '음유시인': 2,
         '생활': 2,
         '대장장이': 2,
         '생전': 2,
         '요리': 2,
         '필사': 2,
         '주자': 2,
         '피하': 2,
         '만남': 2,
         '대로': 2,
         '판매': 2,
         '봉인': 2,
         '거치': 2,
         '사과': 2,
         '길목': 2,
         '나무': 2,
         '루트': 2,
         '슬라임': 2,
         '직행': 2,
         '린다': 2,
         '래서': 2,
         '충족': 2,
         '절망': 2,
         '제목': 2,
         '영어': 2,
         '영문': 2,
         '배포': 2,
         '주로': 2,
         '실수': 2,
         '거의': 2,
         '처리': 2,
         '중이': 2,
         '여러': 2,
         '모서리': 2,
         '프로': 2,
         '참가자': 2,
         '에피소드': 2,
         '공개': 2,
         '정리': 2,
         '먼저': 2,
         '패자': 2,
         '제한': 2,
         '다행': 2,
         '종류': 2,
         '존재': 2,
         '소모': 2,
         '소유권': 2,
         '변경': 2,
         '상대방': 2,
         '상점': 2,
         '점등': 2,
         '바탕': 2,
         '추리': 2,
         '구성': 2,
         '두더지': 2,
         '기회': 2,
         '기념품': 2,
         '운명': 2,
         '보유': 2,
         '성공': 2,
         '불사': 2,
         '재경기': 2,
         '체신': 2,
         '멤버': 2,
         '출생': 2,
         '국적': 2,
         '신체': 2,
         '오른발': 2,
         '보베': 2,
         '로나': 2,
         '편집자': 2,
         '세한': 2,
         '활약': 2,
         '최대': 2,
         '만큼': 2,
         '아웃': 2,
         '구사': 2,
         '유형': 2,
         '플레이메이커': 2,
         '취약': 2,
         '활동량': 2,
         '범위': 2,
         '전방': 2,
         '롱킥': 2,
         '습관': 2,
         '내지': 2,
         '무대': 2,
         '스킬': 2,
         '경전': 2,
         '옐로카드': 2,
         '분명': 2,
         '정신': 2,
         '감치': 2,
         '유독': 2,
         '쿠프': 2,
         '반칙': 2,
         '직후': 2,
         '의문': 2,
         '제기': 2,
         '패배': 2,
         '복부': 2,
         '간의': 2,
         '전체': 2,
         '저번': 2,
         '누적': 2,
         '이미지': 2,
         '역사상': 2,
         '최악': 2,
         '출장': 2,
         '징계': 2,
         '출전': 2,
         '자격': 2,
         '에밀': 2,
         '리아노': 2,
         '대장': 2,
         '전쟁': 2,
         '출신': 2,
         '축구선수': 2,
         '활동': 2,
         '시티': 2,
         '첼시': 2,
         '네시': 2,
         '메디나': 2,
         '니코': 2,
         '파스': 2,
         '로페스': 2,
         '콰르타': 2,
         '고메스': 2,
         '스칼로': 2,
         '기준': 2,
         '커버': 2,
         '막바지': 2,
         '급속도': 2,
         '골프': 2,
         '보디빌더': 2,
         '외손': 2,
         '심부름': 2,
         '진단': 2,
         '일치': 2,
         '명대사': 2,
         '중간': 2,
         '이의': 2,
         '거부': 2,
         '재회': 2,
         '딸봄': 2,
         '윤설': 2,
         '부하': 2,
         '책상': 2,
         '양부모': 2,
         '탈옥': 2,
         '고발': 2,
         '거짓': 2,
         '준비': 2,
         '무너': 2,
         '리기': 2,
         '동영상': 2,
         '서구': 2,
         '장애': 2,
         '증거불충분': 2,
         '경영': 2,
         '참여': 2,
         '체포': 2,
         '윤기': 2,
         '들통': 2,
         '취소': 2,
         '매출': 2,
         '후견인': 2,
         '위기': 2,
         '취하': 2,
         '어차피': 2,
         '횡령': 2,
         '노리': 2,
         '초대': 2,
         '주식': 2,
         '퇴원': 2,
         '녹음': 2,
         '서재': 2,
         '오라': 2,
         '시장': 2,
         '며칠': 2,
         '울분': 2,
         '증언': 2,
         '생사': 2,
         '두절': 2,
         '박람회': 2,
         '비난': 2,
         '끝내': 2,
         '자백': 2,
         '거리': 2,
         '무슨': 2,
         '이제야': 2,
         '주머니': 2,
         '기적': 2,
         '보호자': 2,
         '우연': 2,
         '막장': 2,
         '계단': 2,
         '불안감': 2,
         '오지': 2,
         '박대': 2,
         '최미희': 2,
         '신의': 2,
         '무언가': 2,
         '숨기': 2,
         '어깨': 2,
         '이기': 2,
         '도영은': 2,
         '배신': 2,
         '실로': 2,
         '오자': 2,
         '발견': 2,
         '코웃음': 2,
         '일리': 2,
         '쓴소리': 2,
         '숙소': 2,
         '절대': 2,
         '참회': 2,
         '로부터': 2,
         '핸들': 2,
         '충돌': 2,
         '기절': 2,
         '속죄': 2,
         '본부장': 2,
         '화재': 2,
         '지문': 2,
         '증거물': 2,
         '선물': 2,
         '당시': 2,
         '민박': 2,
         '알츠하이머': 2,
         '후속작': 2,
         '부모': 2,
         ...})

In [43]:
df3 = (
    pd.DataFrame(count3.items(), columns=['word', 'count'])
    .sort_values('count', ascending=False)
    .reset_index(drop=True)
)
df3

        word  count
0         자신    106
1         해주    105
2         마을     96
3         망토     96
4        손여리     79
...      ...    ...
2208     영화관      1
2209  동탄성심병원      1
2210    왼손잡이      1
2211      예외      1
2212     서지석      1

[2213 rows x 2 columns]